#define NA_SE_EN_DODO_J_WALK	    0x3800
#define NA_SE_EN_DODO_J_CRY	    0x3801
#define NA_SE_EN_DODO_J_FIRE	    0x3002
#define NA_SE_EN_DODO_J_DAMAGE	    0x3803
#define NA_SE_EN_DODO_J_DEAD	    0x3804
#define NA_SE_EN_DODO_K_CRY	    0x3805
#define NA_SE_EN_DODO_K_DAMAGE      0x3806
#define NA_SE_EN_DODO_K_DEAD	    0x3807
#define NA_SE_EN_DODO_K_WALK	    0x3808
#define NA_SE_EN_DODO_K_FIRE	    0x3009

#define NA_SE_EN_GOMA_WALK	    0x380A
#define NA_SE_EN_GOMA_HIGH	    0x380B
#define NA_SE_EN_GOMA_CLIM	    0x380C
#define NA_SE_EN_GOMA_DOWN	    0x380D
#define NA_SE_EN_GOMA_CRY1	    0x380E
#define NA_SE_EN_GOMA_CRY2	    0x380F
#define NA_SE_EN_GOMA_DAM1	    0x3810
#define NA_SE_EN_GOMA_DAM2	    0x3811
#define NA_SE_EN_GOMA_DEAD	    0x3812
#define NA_SE_EN_GOMA_UNARI	    0x3813
#define NA_SE_EN_GOMA_BJR_EGG1	    0x3814
#define NA_SE_EN_GOMA_BJR_EGG2	    0x3815
#define NA_SE_EN_GOMA_BJR_WALK	    0x3816
#define NA_SE_EN_GOMA_BJR_CRY	    0x3817
#define NA_SE_EN_GOMA_BJR_DAM1	    0x3818
#define NA_SE_EN_GOMA_BJR_DAM2	    0x3819
#define NA_SE_EN_GOMA_BJR_DEAD	    0x381A
#define NA_SE_EN_GOMA_BJR_FREEZE    0x381F
#define NA_SE_EN_GOMA_BJR_LAND      0x39E3
#define NA_SE_EN_GOMA_BJR_LAND2     0x39E4
#define NA_SE_EN_GOMA_DEMO_EYE	    0x381B
#define NA_SE_EN_GOMA_LAST	    0x301C
#define NA_SE_EN_GOMA_UNARI2	    0x381D
#define NA_SE_EN_GOMA_FAINT	    0x301E

#define NA_SE_EN_GOMA_JR_WALK	    0x395C
#define NA_SE_EN_GOMA_JR_CRY	    0x395D
#define NA_SE_EN_GOMA_JR_DAM1	    0x395E
#define NA_SE_EN_GOMA_JR_DAM2	    0x395F
#define NA_SE_EN_GOMA_JR_DEAD	    0x3960
#define NA_SE_EN_GOMA_JR_FREEZE	    0x389E
#define NA_SE_EN_GOMA_JR_LAND       0x39E5
#define NA_SE_EN_GOMA_JR_LAND2      0x39E6
#define NA_SE_EN_GOMA_EGG1	    0x3961
#define NA_SE_EN_GOMA_EGG2	    0x3962

#define NA_SE_EN_DODO_M_CRY	    0x3820
#define NA_SE_EN_DODO_M_DEAD	    0x3821
#define NA_SE_EN_DODO_M_MOVE	    0x3822
#define NA_SE_EN_DODO_M_DOWN	    0x3823
#define NA_SE_EN_DODO_M_UP	    0x3824
#define NA_SE_EN_DODO_M_GND	    0x387B
#define NA_SE_EN_DODO_M_FREEZE	    0x389E
#define NA_SE_EN_DODO_M_EAT	    0x3826

#define NA_SE_EN_RIZA_CRY	    0x3829
#define NA_SE_EN_RIZA_ATTACK	    0x382A
#define NA_SE_EN_RIZA_DAMAGE	    0x382B
#define NA_SE_EN_RIZA_WARAU	    0x382C
#define NA_SE_EN_RIZA_DEAD	    0x382D
#define NA_SE_EN_RIZA_WALK	    0x382E
#define NA_SE_EN_RIZA_JUMP	    0x382F
#define NA_SE_EN_RIZA_ONGND	    0x3828
#define NA_SE_EN_RIZA_DOWN	    0x387A
#define NA_SE_EN_RIZA_FREEZE	    0x389E

#define NA_SE_EN_STAL_WARAU	    0x3838
#define NA_SE_EN_STAL_SAKEBI	    0x3839
#define NA_SE_EN_STAL_DAMAGE	    0x383A
#define NA_SE_EN_STAL_DEAD	    0x383B
#define NA_SE_EN_STAL_JUMP	    0x386C
#define NA_SE_EN_STAL_WALK	    0x383D
#define NA_SE_EN_STAL_DOWN	    0x387A
#define NA_SE_EN_STAL_LAND	    0x387B
#define NA_SE_EN_STAL_FREEZE	    0x389E

#define NA_SE_EN_FFLY_ATTACK	    0x3840
#define NA_SE_EN_FFLY_FLY	    0x3841
#define NA_SE_EN_FFLY_DEAD	    0x3842
#define NA_SE_EN_FFLY_FREEZE	    0x389E

#define NA_SE_EN_AMOS_WALK	    0x3844
#define NA_SE_EN_AMOS_WAVE	    0x3845
#define NA_SE_EN_AMOS_DEAD	    0x3846
#define NA_SE_EN_AMOS_DAMAGE	    0x3847
#define NA_SE_EN_AMOS_VOICE	    0x3848
#define NA_SE_EN_AMOS_FREEZE	    0x389E

#define NA_SE_EN_DODO_K_COLI	    0x384C
#define NA_SE_EN_DODO_K_COLI2	    0x384D
#define NA_SE_EN_DODO_K_ROLL	    0x304E
#define NA_SE_EN_DODO_K_BREATH	    0x304F
#define NA_SE_EN_DODO_K_DRINK	    0x3850
#define NA_SE_EN_DODO_K_DOWN	    0x3051
#define NA_SE_EN_DODO_K_OTAKEBI	    0x3852
#define NA_SE_EN_DODO_K_END	    0x3853
#define NA_SE_EN_DODO_K_LAST	    0x3054
#define NA_SE_EN_DODO_K_LAVA	    0x3855

#define NA_SE_EN_DODO_J_BREATH	    0x3058
#define NA_SE_EN_DODO_J_TAIL	    0x3859
#define NA_SE_EN_DODO_J_DOWN	    0x387A
#define NA_SE_EN_DODO_J_FREEZE	    0x389E
#define NA_SE_EN_DODO_J_EAT	    0x385B
#define NA_SE_EN_DODO_J_LAND	    0x387A

#define NA_SE_EN_DEKU_MOUTH	    0x385C
#define NA_SE_EN_DEKU_ATTACK	    0x385D
#define NA_SE_EN_DEKU_DAMAGE	    0x385E
#define NA_SE_EN_DEKU_DEAD	    0x385F
#define NA_SE_EN_DEKU_JR_MOUTH	    0x3860
#define NA_SE_EN_DEKU_JR_ATTACK	    0x3861
#define NA_SE_EN_DEKU_JR_DEAD	    0x3862
#define NA_SE_EN_DEKU_SCRAPE	    0x3863
#define NA_SE_EN_DEKU_FALL	    0x387B
#define NA_SE_EN_DEKU_FREEZE	    0x389E
#define NA_SE_EN_DEKU_WAKEUP	    0x39E2

#define NA_SE_EN_TAIL_FLY	    0x3064
#define NA_SE_EN_TAIL_CRY	    0x3865
#define NA_SE_EN_TAIL_DEAD	    0x3866
#define NA_SE_EN_TAIL_FREEZE	    0x389E

#define NA_SE_EN_STALTU_DOWN	    0x3868
#define NA_SE_EN_STALTU_UP	    0x3869
#define NA_SE_EN_STALTU_LAUGH	    0x386A
#define NA_SE_EN_STALTU_DAMAGE	    0x386B
#define NA_SE_EN_STALTU_FREEZE	    0x389E
#define NA_SE_EN_STALTU_WAVE	    0x39E0
#define NA_SE_EN_STALTU_DOWN_SET    0x39E1

#define NA_SE_EN_STALWALL_LAND	    0x387B
#define NA_SE_EN_STALWALL_LAUGH	    0x39F2
#define NA_SE_EN_STALWALL_DEAD	    0x3885

#define NA_SE_EN_TEKU_JUMP	    0x386C
#define NA_SE_EN_TEKU_LAND	    0x387B
#define NA_SE_EN_TEKU_DEAD	    0x386E
#define NA_SE_EN_TEKU_DAMAGE	    0x386D
#define NA_SE_EN_TEKU_WALK	    0x386F
#define NA_SE_EN_TEKU_WALK_WATER    0x3835
#define NA_SE_EN_TEKU_JUMP_WATER    0x388E
#define NA_SE_EN_TEKU_LAND_WATER    0x388A
#define NA_SE_EN_TEKU_LAND_WATER2   0x388F
#define NA_SE_EN_TEKU_FREEZE        0x389E
#define NA_SE_EN_TEKU_REVERSE       0x3888

#define NA_SE_EN_PO_KANTERA	    0x3870
#define NA_SE_EN_PO_FLY	            0x3071
#define NA_SE_EN_PO_AWAY	    0x3072
#define NA_SE_EN_PO_APPEAR	    0x3873
#define NA_SE_EN_PO_DISAPPEAR	    0x3874
#define NA_SE_EN_PO_DAMAGE	    0x3875
#define NA_SE_EN_PO_DEAD	    0x3876
#define NA_SE_EN_PO_DEAD2	    0x3877

#define NA_SE_EN_EXTINCT	    0x3878

#define NA_SE_EN_NUTS_UP	    0x387C
#define NA_SE_EN_NUTS_DOWN	    0x387D
#define NA_SE_EN_NUTS_THROW	    0x387E
#define NA_SE_EN_NUTS_WALK	    0x387F
#define NA_SE_EN_NUTS_DAMAGE	    0x3880
#define NA_SE_EN_NUTS_DEAD	    0x3881
#define NA_SE_EN_NUTS_FAINT	    0x3882
#define NA_SE_EN_NUTS_FREEZE	    0x389E
#define NA_SE_EN_NUTS_CUTBODY	    0x393B

#define NA_SE_EN_AKINDONUTS_HIDE    0x3987

#define NA_SE_EN_STALTU_ROLL	    0x3884
#define NA_SE_EN_STALTU_DEAD	    0x3885

#define NA_SE_EN_FALL_AIM	    0x3890
#define NA_SE_EN_FALL_UP	    0x3891
#define NA_SE_EN_FALL_CATCH	    0x3892
#define NA_SE_EN_FALL_LAND	    0x3893
#define NA_SE_EN_FALL_WALK	    0x3894
#define NA_SE_EN_FALL_DAMAGE	    0x3895
#define NA_SE_EN_FALL_DEAD	    0x3896
#define NA_SE_EN_FALL_FREEZE	    0x389E
#define NA_SE_EN_FALL_LAND2         0x387B

#define NA_SE_EN_BIRI_FLY	    0x3898
#define NA_SE_EN_BIRI_JUMP	    0x3899
#define NA_SE_EN_BIRI_SPARK	    0x309A
#define NA_SE_EN_BIRI_DEAD	    0x389B
#define NA_SE_EN_BIRI_BUBLE	    0x389C
#define NA_SE_EN_BIRI_LAND	    0x387B
#define NA_SE_EN_BIRI_FREEZE	    0x389E

#define NA_SE_EN_BARI_ROLL	    0x389D
#define NA_SE_EN_BARI_FAINT	    0x389E
#define NA_SE_EN_BARI_DEAD	    0x389F
#define NA_SE_EN_BARI_SPLIT	    0x3887
#define NA_SE_EN_BARI_LAND	    0x387B
#define NA_SE_EN_BARI_SPARK	    0x309A
#define NA_SE_EN_BARI_DAMAGE	    0x38DC

#define NA_SE_EN_FANTOM_TRANSFORM   0x38A1
#define NA_SE_EN_FANTOM_THUNDER	    0x38A2
#define NA_SE_EN_FANTOM_SPARK	    0x38A3
#define NA_SE_EN_FANTOM_FLOAT	    0x30A4
#define NA_SE_EN_FANTOM_MASIC1	    0x38A5
#define NA_SE_EN_FANTOM_MASIC2	    0x38A6
#define NA_SE_EN_FANTOM_FIRE	    0x30A7
#define NA_SE_EN_FANTOM_HIT_THUNDER 0x38A8
#define NA_SE_EN_FANTOM_ATTACK	    0x38A9
#define NA_SE_EN_FANTOM_STICK       0x38AA
#define NA_SE_EN_FANTOM_EYE         0x38AB
#define NA_SE_EN_FANTOM_LAST        0x38AC
#define NA_SE_EN_FANTOM_THUNDER_GND 0x38AD
#define NA_SE_EN_FANTOM_DAMAGE      0x38AE
#define NA_SE_EN_FANTOM_DEAD        0x38AF
#define NA_SE_EN_FANTOM_LAUGH       0x38B0
#define NA_SE_EN_FANTOM_DAMAGE2     0x38B1
#define NA_SE_EN_FANTOM_VOICE       0x38B2
#define NA_SE_EN_FANTOM_ST_LAUGH    0x39D6

#define NA_SE_EN_MORIBLIN_WALK      0x38B8
#define NA_SE_EN_MORIBLIN_SLIDE     0x38B9
#define NA_SE_EN_MORIBLIN_ATTACK    0x38BA
#define NA_SE_EN_MORIBLIN_VOICE     0x38BB
#define NA_SE_EN_MORIBLIN_SPEAR_AT  0x38BC
#define NA_SE_EN_MORIBLIN_SPEAR_NORM 0x38BD
#define NA_SE_EN_MORIBLIN_DEAD      0x38BE
#define NA_SE_EN_MORIBLIN_DASH      0x38BF
#define NA_SE_EN_MORIBLIN_LAND      0x387A
#define NA_SE_EN_MORIBLIN_FREEZE    0x389E

#define NA_SE_EN_OCTAROCK_THROW     0x387E
#define NA_SE_EN_OCTAROCK_ROCK      0x38C0
#define NA_SE_EN_OCTAROCK_FLOAT     0x38C1
#define NA_SE_EN_OCTAROCK_JUMP      0x38C2
#define NA_SE_EN_OCTAROCK_LAND      0x38C3
#define NA_SE_EN_OCTAROCK_SINK      0x38C4
#define NA_SE_EN_OCTAROCK_BUBLE     0x38C5
#define NA_SE_EN_OCTAROCK_DEAD1     0x38C6
#define NA_SE_EN_OCTAROCK_DEAD2     0x38C7

#define NA_SE_EN_BUBLE_WING        0x38C8
#define NA_SE_EN_BUBLE_MOUTH       0x38C9
#define NA_SE_EN_BUBLE_LAUGH       0x38CA
#define NA_SE_EN_BUBLE_BITE        0x38CB
#define NA_SE_EN_BUBLE_UP          0x38CC
#define NA_SE_EN_BUBLE_DOWN        0x38CD
#define NA_SE_EN_BUBLE_DEAD        0x38CE
#define NA_SE_EN_BUBLE_LAND        0x387B
#define NA_SE_EN_BUBLE_FREEZE      0x389E
#define NA_SE_EN_BUBLE_DAMAGE      0x38E3

#define NA_SE_EN_BUBLEFALL_FIRE    0x30CF

#define NA_SE_EN_VALVAISA_APPEAR    0x30D0
#define NA_SE_EN_VALVAISA_ROAR      0x38D1
#define NA_SE_EN_VALVAISA_MAHI1     0x38D2
#define NA_SE_EN_VALVAISA_MAHI2     0x38D3
#define NA_SE_EN_VALVAISA_KNOCKOUT  0x38D4
#define NA_SE_EN_VALVAISA_DAMAGE1   0x38D5
#define NA_SE_EN_VALVAISA_DAMAGE2   0x38D6
#define NA_SE_EN_VALVAISA_ROCK      0x38D7
#define NA_SE_EN_VALVAISA_LAND      0x3927
#define NA_SE_EN_VALVAISA_DEAD      0x38D9
#define NA_SE_EN_VALVAISA_BURN      0x30DA
#define NA_SE_EN_VALVAISA_FIRE      0x30DB
#define NA_SE_EN_VALVAISA_LAND2     0x3889
#define NA_SE_EN_VALVAISA_SW_NAIL   0x38D8

#define NA_SE_EN_MONBLIN_HAM_LAND   0x39EF
#define NA_SE_EN_MONBLIN_HAM_DOWN   0x38E1
#define NA_SE_EN_MONBLIN_HAM_UP     0x38E2
#define NA_SE_EN_MONBLIN_GNDWAVE    0x30E0
#define NA_SE_EN_MONBLIN_FREEZE     0x389E

#define NA_SE_EN_REDEAD_CRY         0x38E4
#define NA_SE_EN_REDEAD_AIM         0x38E5
#define NA_SE_EN_REDEAD_DAMAGE      0x38E6
#define NA_SE_EN_REDEAD_LAND        0x387A
#define NA_SE_EN_REDEAD_DEAD        0x38E7
#define NA_SE_EN_REDEAD_ATTACK      0x38E8

#define NA_SE_EN_PO_LAUGH	    0x38EC
#define NA_SE_EN_PO_CRY  	    0x38ED
#define NA_SE_EN_PO_ROLL  	    0x38EE
#define NA_SE_EN_PO_LAUGH2  	    0x38EF
#define NA_SE_EN_PO_SISTER_DEAD	    0x3886

#define NA_SE_EN_PO_BIG_GET	    0x3883
#define NA_SE_EN_PO_BIG_AWAY	    0x38EC
#define NA_SE_EN_PO_BIG_CRY	    0x31E8

#define NA_SE_EN_MOFER_APPEAR  	    0x30F0
#define NA_SE_EN_MOFER_ATTACK  	    0x30F1
#define NA_SE_EN_MOFER_WAVE  	    0x38F2
#define NA_SE_EN_MOFER_CATCH  	    0x38F3
#define NA_SE_EN_MOFER_CORE_DAMAGE  0x39EC
#define NA_SE_EN_MOFER_CUT          0x38F4
#define NA_SE_EN_MOFER_MOVE_DEMO    0x30F5
#define NA_SE_EN_MOFER_BUBLE_DEMO   0x38F6
#define NA_SE_EN_MOFER_CORE_JUMP    0x38F7
#define NA_SE_EN_MOFER_DEAD         0x30F8
#define NA_SE_EN_MOFER_LASTVOICE    0x38F9
#define NA_SE_EN_MOFER_CORE_ROLL    0x30FA
#define NA_SE_EN_MOFER_CORE_FLY     0x38FB
#define NA_SE_EN_MOFER_CORE_LAND    0x38DD
#define NA_SE_EN_MOFER_CORE_MOVE_WT 0x38DE
#define NA_SE_EN_MOFER_CORE_SMJUMP  0x38DF

#define NA_SE_EN_GOLON_WAKE_UP      0x38FC
#define NA_SE_EN_GOLON_SIT_DOWN     0x38FD
#define NA_SE_EN_GOLON_HARD         0x387B
#define NA_SE_EN_GOLON_WALK         0x38B8
#define NA_SE_EN_GOLON_LAND         0x387B
#define NA_SE_EN_GOLON_LAND_BIG     0x3879
#define NA_SE_EN_GOLON_WAKE_UP_BIG  0x38FC
#define NA_SE_EN_GOLON_SIT_DOWN_BIG 0x38FD
#define NA_SE_EN_GOLON_EYE_BIG      0x391C
#define NA_SE_EN_GOLON_GOOD_BIG     0x391D
#define NA_SE_EN_GOLON_CRY          0x39EB

#define NA_SE_EN_DEADHAND_BITE      0x3900
#define NA_SE_EN_DEADHAND_WALK      0x3901
#define NA_SE_EN_DEADHAND_GRIP      0x3902
#define NA_SE_EN_DEADHAND_HAND_AT   0x3903
#define NA_SE_EN_DEADHAND_HIDE      0x39A8
#define NA_SE_EN_DEADHAND_DAMAGE    0x39A9
#define NA_SE_EN_DEADHAND_HAND_DEAD 0x39AA
#define NA_SE_EN_DEADHAND_DEAD      0x39AB
#define NA_SE_EN_DEADHAND_LAND      0x387A
#define NA_SE_EN_DEADHAND_LAUGH     0x39A7
#define NA_SE_EN_DEADHAND_FREEZE    0x389E

#define NA_SE_EN_LAST_DAMAGE        0x388B

#define NA_SE_EN_DAIOCTA_MAHI       0x3904
#define NA_SE_EN_DAIOCTA_SPLASH     0x3105
#define NA_SE_EN_DAIOCTA_VOICE      0x3906
#define NA_SE_EN_DAIOCTA_DAMAGE     0x3907
#define NA_SE_EN_DAIOCTA_SINK       0x3908
#define NA_SE_EN_DAIOCTA_DEAD       0x3909
#define NA_SE_EN_DAIOCTA_DEAD2      0x390A
#define NA_SE_EN_DAIOCTA_JUMP       0x386C
#define NA_SE_EN_DAIOCTA_LAND_WATER 0x39ED
#define NA_SE_EN_DAIOCTA_LAND       0x3879

#define NA_SE_EN_STALWALL_ROLL	    0x388C
#define NA_SE_EN_STALWALL_DASH	    0x388D

#define NA_SE_EN_STALGOLD_ROLL	    0x39DA
#define NA_SE_EN_STALGOLD_UP	    0x3824
#define NA_SE_EN_STALGOLD_UP_CRY    0x39EA
#define NA_SE_EN_STALGOLD_LAND      0x387B

#define NA_SE_EN_MUSI_LAND	    0x39A0
#define NA_SE_EN_MUSI_SINK	    0x39E9
#define NA_SE_EN_MUSI_WALK	    0x39F0

#define NA_SE_EN_TWINROBA_APPEAR_MS     0x390C
#define NA_SE_EN_TWINROBA_TRANSFORM     0x390D
#define NA_SE_EN_TWINROBA_MS_FIRE       0x310E
#define NA_SE_EN_TWINROBA_FIRE_EXP      0x310F
#define NA_SE_EN_TWINROBA_SHOOT_FREEZE  0x3111
#define NA_SE_EN_TWINROBA_MS_FREEZE     0x3112
#define NA_SE_EN_TWINROBA_MASIC_SET     0x3913
#define NA_SE_EN_TWINROBA_LAUGH         0x39B0
#define NA_SE_EN_TWINROBA_SHOOT_VOICE   0x39B3
#define NA_SE_EN_TWINROBA_DAMAGE_VOICE  0x3916
#define NA_SE_EN_TWINROBA_REFL_FIRE     0x3117
#define NA_SE_EN_TWINROBA_REFL_FREEZE   0x3118
#define NA_SE_EN_TWINROBA_YOUNG_LAUGH   0x39B9
#define NA_SE_EN_TWINROBA_YOUNG_DAMAGE  0x391A
#define NA_SE_EN_TWINROBA_YOUNG_DEAD    0x391B
#define NA_SE_EN_TWINROBA_FB_FLY        0x391E
#define NA_SE_EN_TWINROBA_FLY           0x311F
#define NA_SE_EN_TWINROBA_FADEOUT_DEMO  0x3877
#define NA_SE_EN_TWINROBA_FADEOUT2_DEMO 0x38CD
#define NA_SE_EN_TWINROBA_AP_LB_DEMO    0x38A5
#define NA_SE_EN_TWINROBA_FLY_LB_DEMO   0x30A7
#define NA_SE_EN_TWINROBA_HIT_LB_DEMO   0x38A8
#define NA_SE_EN_TWINROBA_LB_VOICE_DEMO 0x39B3
#define NA_SE_EN_TWINROBA_FLY_DEMO      0x317B
#define NA_SE_EN_TWINROBA_UNARI         0x3120
#define NA_SE_EN_TWINROBA_ROLL          0x3921
#define NA_SE_EN_TWINROBA_SHOOT_FIRE    0x3122
#define NA_SE_EN_TWINROBA_THROW_MASIC   0x3923
#define NA_SE_EN_TWINROBA_POWERUP       0x3910
#define NA_SE_EN_TWINROBA_YOUNG_SHOOTVC 0x39B8
#define NA_SE_EN_TWINROBA_YOUNG_DAMAGE2 0x39B7
#define NA_SE_EN_TWINROBA_LAUGH2        0x39B1
#define NA_SE_EN_TWINROBA_SENSE         0x39B4
#define NA_SE_EN_TWINROBA_DIE           0x39B5
#define NA_SE_EN_TWINROBA_YOUNG_WINK    0x39BB
#define NA_SE_EN_TWINROBA_CUTBODY       0x3914
#define NA_SE_EN_TWINROBA_FIGHT         0x31E7

#define NA_SE_EN_DARUNIA_HIT_BREAST 0x3124
#define NA_SE_EN_DARUNIA_HIT_LINK   0x3925
#define NA_SE_EN_DARUNIA_LAND       0x3879

#define NA_SE_EN_IRONNACK_WALK             0x3928
#define NA_SE_EN_IRONNACK_SWING_AXE        0x3929
#define NA_SE_EN_IRONNACK_ARMOR_DEMO       0x392A
#define NA_SE_EN_IRONNACK_APPEAR_AXE_DEMO  0x390D
#define NA_SE_EN_IRONNACK_FINGER_DEMO      0x3939
#define NA_SE_EN_IRONNACK_GRIP_AXE_DEMO    0x392A
#define NA_SE_EN_IRONNACK_WAVE_DEMO        0x3938
#define NA_SE_EN_IRONNACK_STAGGER_DEMO     0x392B
#define NA_SE_EN_IRONNACK_ARMOR_OFF_DEMO   0x392C
#define NA_SE_EN_IRONNACK_ARMOR_LAND1_DEMO 0x392D
#define NA_SE_EN_IRONNACK_ARMOR_LAND2_DEMO 0x392E
#define NA_SE_EN_IRONNACK_ARMOR_LAND3_DEMO 0x392F
#define NA_SE_EN_IRONNACK_ARMOR_HIT        0x393A
#define NA_SE_EN_IRONNACK_DAMAGE           0x39BE
#define NA_SE_EN_IRONNACK_DEAD             0x39C0
#define NA_SE_EN_IRONNACK_BREAK_PILLAR     0x39AD
#define NA_SE_EN_IRONNACK_HIT_GND          0x39AE
#define NA_SE_EN_IRONNACK_FREEZE           0x389E
#define NA_SE_EN_IRONNACK_DASH             0x39BF
#define NA_SE_EN_IRONNACK_WAKEUP           0x39C2
#define NA_SE_EN_IRONNACK_PULLOUT          0x39C1
#define NA_SE_EN_IRONNACK_BREAK_PILLAR2    0x39AC
#define NA_SE_EN_IRONNACK_CUTBODY          0x393B
#define NA_SE_EN_IRONNACK_WAKEUP_DEMO      0x39C2
#define NA_SE_EN_IRONNACK_DEAD_DEMO        0x39C0

#define NA_SE_EN_GANON_ATTACK_DEMO       0x30B4
#define NA_SE_EN_GANON_FIRE_DEMO         0x38B5
#define NA_SE_EN_GANON_HIT_THUNDER_DEMO  0x38A8

#define NA_SE_EN_CHICKEN_FLUTTER    0x38FF

#define NA_SE_EN_FLOORMASTER_ATTACK     0x3930
#define NA_SE_EN_FLOORMASTER_SM_WALK    0x3931
#define NA_SE_EN_FLOORMASTER_SM_DEAD    0x3932
#define NA_SE_EN_FLOORMASTER_RESTORE    0x3133
#define NA_SE_EN_FLOORMASTER_EXPAND     0x3934
#define NA_SE_EN_FLOORMASTER_SPLIT      0x3935
#define NA_SE_EN_FLOORMASTER_SM_STICK   0x3136
#define NA_SE_EN_FLOORMASTER_DEAD       0x3896
#define NA_SE_EN_FLOORMASTER_DAMAGE     0x3895
#define NA_SE_EN_FLOORMASTER_WALK       0x3894
#define NA_SE_EN_FLOORMASTER_LAND       0x3893
#define NA_SE_EN_FLOORMASTER_LAND2      0x387B
#define NA_SE_EN_FLOORMASTER_SLIDING    0x3034
#define NA_SE_EN_FLOORMASTER_SM_LAND    0x3937
#define NA_SE_EN_FLOORMASTER_SM_LAND2   0x387B
#define NA_SE_EN_FLOORMASTER_FREEZE     0x389E
#define NA_SE_EN_FLOORMASTER_SM_FREEZE  0x389E

#define NA_SE_EN_BALINADE_LEVEL     0x313C
#define NA_SE_EN_BALINADE_DAMAGE    0x393D
#define NA_SE_EN_BALINADE_FAINT     0x393E
#define NA_SE_EN_BALINADE_BREAK     0x393F
#define NA_SE_EN_BALINADE_DEAD      0x3940
#define NA_SE_EN_BALINADE_STICK     0x3941
#define NA_SE_EN_BALINADE_THUNDER   0x3942
#define NA_SE_EN_BALINADE_BL_SPARK  0x3143
#define NA_SE_EN_BALINADE_BL_DEAD   0x3944
#define NA_SE_EN_BALINADE_BREAK2    0x3945
#define NA_SE_EN_BALINADE_HIT_RINK  0x3946

#define NA_SE_EN_BALINADE_HAND_DOWN    0x3958
#define NA_SE_EN_BALINADE_HAND_UP      0x3959
#define NA_SE_EN_BALINADE_HAND_DAMAGE  0x395A
#define NA_SE_EN_BALINADE_HAND_DEAD    0x395B

#define NA_SE_EN_AWA_BOUND          0x3948
#define NA_SE_EN_AWA_BREAK          0x3949

#define NA_SE_EN_EIER_DAMAGE        0x394C
#define NA_SE_EN_EIER_DEAD          0x394D
#define NA_SE_EN_EIER_FAINT         0x389E
#define NA_SE_EN_EIER_FLUTTER       0x394E
#define NA_SE_EN_EIER_FLY           0x314F
#define NA_SE_EN_EIER_UP            0x38C2
#define NA_SE_EN_EIER_DOWN          0x38C4
#define NA_SE_EN_EIER_LAND          0x387B
#define NA_SE_EN_EIER_ATTACK        0x39A2
#define NA_SE_EN_EIER_CRY           0x39A3

#define NA_SE_EN_SHADEST_TAIKO_LOW     0x3950
#define NA_SE_EN_SHADEST_TAIKO_HIGH    0x3951
#define NA_SE_EN_SHADEST_CLAP          0x3952
#define NA_SE_EN_SHADEST_FLY_ATTACK    0x3953
#define NA_SE_EN_SHADEST_HAND_WAVE     0x3964
#define NA_SE_EN_SHADEST_CATCH         0x3965
#define NA_SE_EN_SHADEST_GRIP          0x3965
#define NA_SE_EN_SHADEST_HAND_FLY      0x3167
#define NA_SE_EN_SHADEST_SHAKEHAND     0x3968
#define NA_SE_EN_SHADEST_DAMAGE        0x3969
#define NA_SE_EN_SHADEST_DAMAGE_HAND   0x396A
#define NA_SE_EN_SHADEST_DISAPPEAR     0x396B
#define NA_SE_EN_SHADEST_MOVE          0x318D
#define NA_SE_EN_SHADEST_FREEZE        0x396E
#define NA_SE_EN_SHADEST_DEAD          0x396F
#define NA_SE_EN_SHADEST_LAST          0x318C
#define NA_SE_EN_SHADEST_PRAY          0x398E
#define NA_SE_EN_SHADEST_LAND          0x3966


#define NA_SE_EN_OWL_FLUTTER        0x3926

#define NA_SE_EN_PIHAT_UP           0x3954
#define NA_SE_EN_PIHAT_FLY          0x3155
#define NA_SE_EN_PIHAT_DAMAGE       0x3956
#define NA_SE_EN_PIHAT_LAND         0x3957
#define NA_SE_EN_PIHAT_FREEZE       0x389E
#define NA_SE_EN_PIHAT_SM_FLY       0x3184
#define NA_SE_EN_PIHAT_SM_DEAD      0x3985
#define NA_SE_EN_PIHAT_SM_FREEZE    0x389E

#define NA_SE_EN_BROB_WAVE          0x394A
#define NA_SE_EN_BROB_FREEZE        0x389E

#define NA_SE_EN_BIMOS_ROLL_HEAD    0x3170
#define NA_SE_EN_BIMOS_LAZER        0x3171
#define NA_SE_EN_BIMOS_LAZER_GND    0x3172
#define NA_SE_EN_BIMOS_AIM          0x3973
#define NA_SE_EN_BIMOS_FREEZE       0x389E

#define NA_SE_EN_BUBLEWALK_WALK     0x3974
#define NA_SE_EN_BUBLEWALK_AIM      0x3975
#define NA_SE_EN_BUBLEWALK_REVERSE  0x3976
#define NA_SE_EN_BUBLEWALK_DAMAGE   0x3977
#define NA_SE_EN_BUBLEWALK_DEAD     0x3978
#define NA_SE_EN_BUBLEWALK_JUMP     0x386C
#define NA_SE_EN_BUBLEWALK_LAND     0x387B
#define NA_SE_EN_BUBLEWALK_FREEZE   0x389E

#define NA_SE_EN_YUKABYUN_FLY       0x3179
#define NA_SE_EN_YUKABYUN_BREAK     0x38C0

#define NA_SE_EN_FLAME_KICK         0x397C
#define NA_SE_EN_FLAME_RUN          0x317D
#define NA_SE_EN_FLAME_ROLL         0x317E
#define NA_SE_EN_FLAME_MAN_RUN      0x397F
#define NA_SE_EN_FLAME_MAN_DAMAGE   0x3980
#define NA_SE_EN_FLAME_LAUGH        0x3981
#define NA_SE_EN_FLAME_MAN_SLIDE    0x3982
#define NA_SE_EN_FLAME_FIRE_ATTACK  0x3183
#define NA_SE_EN_FLAME_MAN_JUMP     0x386C
#define NA_SE_EN_FLAME_MAN_LAND     0x387B
#define NA_SE_EN_FLAME_FREEZE       0x389E
#define NA_SE_EN_FLAME_MAN_SURP     0x398B
#define NA_SE_EN_FLAME_DAMAGE       0x397A

#define NA_SE_EN_RIVA_APPEAR        0x3986
#define NA_SE_EN_RIVA_HIDE          0x3987
#define NA_SE_EN_RIVA_DAMAGE        0x3988
#define NA_SE_EN_RIVA_DEAD          0x3989
#define NA_SE_EN_RIVA_MOVE          0x398A
#define NA_SE_EN_RIVA_FREEZE        0x389E
#define NA_SE_EN_RIVA_BIG_APPEAR    0x39EE

#define NA_SE_EN_LIKE_WALK          0x3990
#define NA_SE_EN_LIKE_UNARI         0x3991
#define NA_SE_EN_LIKE_DRINK         0x3992
#define NA_SE_EN_LIKE_EAT           0x3993
#define NA_SE_EN_LIKE_THROW         0x3994
#define NA_SE_EN_LIKE_DAMAGE        0x3995
#define NA_SE_EN_LIKE_DEAD          0x3996
#define NA_SE_EN_LIKE_FREEZE        0x389E

#define NA_SE_EN_GERUDOFT_ATTACK    0x3998
#define NA_SE_EN_GERUDOFT_DAMAGE    0x3999
#define NA_SE_EN_GERUDOFT_DEAD      0x399A
#define NA_SE_EN_GERUDOFT_BREATH    0x39C6
#define NA_SE_EN_GERUDOFT_DOWN      0x387A
#define NA_SE_EN_GERUDOFT_WALK      0x39A0
#define NA_SE_EN_GERUDOFT_JUMP      0x386C
#define NA_SE_EN_GERUDOFT_FREEZE    0x389E
#define NA_SE_EN_GERUDOFT_LAUGH     0x39B9

#define NA_SE_EN_ANUBIS_FIRE        0x319C
#define NA_SE_EN_ANUBIS_FIREBOMB    0x399D
#define NA_SE_EN_ANUBIS_DAMAGE      0x393B
#define NA_SE_EN_ANUBIS_DEAD        0x399F

#define NA_SE_EN_LIGHT_ARROW_HIT    0x3836

#define NA_SE_EN_FREEZAD_BREATH     0x31A4
#define NA_SE_EN_FREEZAD_DAMAGE     0x39A5
#define NA_SE_EN_FREEZAD_DEAD       0x39A6

#define NA_SE_EN_TUBOOCK_FLY        0x3037

#define NA_SE_EN_GANON_LAUGH        0x39C7
#define NA_SE_EN_GANON_VOICE_DEMO   0x39C8
#define NA_SE_EN_GANON_THROW        0x39C9
#define NA_SE_EN_GANON_AT_RETURN    0x39CA
#define NA_SE_EN_GANON_HIT_GND      0x39CB
#define NA_SE_EN_GANON_DAMAGE1      0x39CC
#define NA_SE_EN_GANON_DAMAGE2      0x39CD
#define NA_SE_EN_GANON_DOWN         0x39CE
#define NA_SE_EN_GANON_RESTORE      0x39CF
#define NA_SE_EN_GANON_DEAD         0x39D0
#define NA_SE_EN_GANON_BREATH       0x39D1
#define NA_SE_EN_GANON_TOKETU       0x39D2
#define NA_SE_EN_GANON_CASBREAK     0x39D3
#define NA_SE_EN_GANON_BIGMASIC     0x39D4
#define NA_SE_EN_GANON_DARKWAVE     0x39D5
#define NA_SE_EN_GANON_LAUGH_MID    0x39D6

#define NA_SE_EN_GANON_THROW_MASIC  0x3825
#define NA_SE_EN_GANON_DD_THUNDER   0x3827
#define NA_SE_EN_GANON_FLOAT        0x3056
#define NA_SE_EN_GANON_DARKWAVE_M   0x3057
#define NA_SE_EN_GANON_SPARK        0x3867
#define NA_SE_EN_GANON_FIRE         0x30A0
#define NA_SE_EN_GANON_HIT_THUNDER  0x390B
#define NA_SE_EN_GANON_HIT_GND_IMP  0x3915
#define NA_SE_EN_GANON_CUTBODY      0x3919
#define NA_SE_EN_GANON_WAVE_GND     0x3147
#define NA_SE_EN_GANON_BODY_SPARK   0x3163
#define NA_SE_EN_GANON_CHARGE_MASIC 0x316C
#define NA_SE_EN_GANON_THROW_BIG    0x396D
#define NA_SE_EN_MGANON_ROAR        0x398F
#define NA_SE_EN_MGANON_SWORD       0x3997
#define NA_SE_EN_MGANON_DAMAGE      0x399B
#define NA_SE_EN_MGANON_WALK        0x39D7
#define NA_SE_EN_MGANON_DEAD1       0x399E
#define NA_SE_EN_MGANON_BREATH      0x39AF
#define NA_SE_EN_MGANON_DEAD2       0x39A1
#define NA_SE_EN_MGANON_STAND       0x39D8
#define NA_SE_EN_MGANON_UNARI       0x39D9
#define NA_SE_EN_MGANON_SWDIMP      0x39DF

#define NA_SE_EN_SHELL_MOUTH        0x3849
#define NA_SE_EN_SHELL_DEAD         0x384A
#define NA_SE_EN_SHELL_LAND         0x387B

#define NA_SE_EN_NYU_MOVE           0x30E9
#define NA_SE_EN_NYU_HIT_STOP       0x38EA
#define NA_SE_EN_NYU_LAND           0x387B
#define NA_SE_EN_NYU_DEAD           0x394B

#define NA_SE_EN_STALKID_WALK       0x3830
#define NA_SE_EN_STALKID_ATTACK     0x3831
#define NA_SE_EN_STALKID_DAMAGE     0x3832
#define NA_SE_EN_STALKID_DEAD       0x3833
#define NA_SE_EN_STALKID_APPEAR     0x3986
#define NA_SE_EN_STALKID_HIDE       0x3987
#define NA_SE_EN_STALKID_FREEZE     0x389E

#define NA_SE_EN_WOLFOS_CRY         0x383E
#define NA_SE_EN_WOLFOS_ATTACK      0x383F
#define NA_SE_EN_WOLFOS_DAMAGE      0x3843
#define NA_SE_EN_WOLFOS_DEAD        0x384B
#define NA_SE_EN_WOLFOS_WALK        0x385A
#define NA_SE_EN_WOLFOS_FREEZE      0x389E
#define NA_SE_EN_WOLFOS_JUMP        0x386C
#define NA_SE_EN_WOLFOS_APPEAR      0x383C

#define NA_SE_EN_KAICHO_CRY         0x38B6
#define NA_SE_EN_KAICHO_ATTACK      0x38B7
#define NA_SE_EN_KAICHO_DAMAGE      0x38B3
#define NA_SE_EN_KAICHO_DEAD        0x38EB
#define NA_SE_EN_KAICHO_FLUTTER     0x3897
#define NA_SE_EN_KAICHO_FREEZE      0x389E

#define NA_SE_EN_MIMICK_BREATH      0x31F1

#define NA_SE_EN_KDOOR_WAVE         0x39DB
#define NA_SE_EN_KDOOR_HIT          0x39DC
#define NA_SE_EN_KDOOR_BREAK        0x39DD
#define NA_SE_EN_KDOOR_HIT_GND      0x39DE

