#!/bin/csh
# $Header: D:\Downloads\bbgames\bbgames\d1\routefree\bbgames\depot\/z_ocarina2/shape2/u64tools/u64cc,v 1.1 2003/03/14 20:03:29 tong Exp $
#
# シェイプデータ生成
# ディレクトリ名.o
#
 set echo
unalias *
#set nonomatch

if ( $?VF3DEXOPT == 0 ) then
  setenv VF3DEXOPT
  setenv VF3DEXOPT '-DF3DEX_GBI_2'
endif

set PATCH_DIR = /usr/local/srd/PR/patch/PR
set LIBC64_DIR = /usr/local/srd/PR
set COPT = "-G 0 -fullwarn -xansi -Xcpluscomm -non_shared -mips2 -o32 -nostdinc -I$PATCH_DIR -I$PATCH_DIR/.. -I$LIBC64_DIR -I$ZELDA_ROOT/src -I/usr/local/srd/PR -I/usr/include/PR -I/usr/include -DF3DEX_GBI $VF3DEXOPT"
set LD = /usr/lib/PR/nld
set CC = /usr/bin/cc

set out=`pwd`

rm -f *.o $out:t.oo $out:t.map

echo $CC $COPT -c *.c
     $CC $COPT -c *.c
echo $LD -wall -r *.o -o $out:t.oo -m \> $out:t.map
     $LD -wall -r *.o -o $out:t.oo -m  > $out:t.map
     cp $out:t.oo $out:t.o
     nm $out:t.o  | grep " U "

exit 0
