#!/bin/csh -f 
# $Header: D:\Downloads\bbgames\bbgames\d1\routefree\bbgames\depot\/z_ocarina2/shape2/u64tools/u64ccsall,v 1.1 2003/03/14 20:03:29 tong Exp $

foreach f ( * )
	if ( -d $f ) then
		cd $f
		echo u64ccs
 			 u64ccs
		cd ..
	endif
end
