#!/bin/csh
# $Header: D:\Downloads\bbgames\bbgames\d1\routefree\bbgames\depot\/z_ocarina2/shape2/u64tools/u64txt,v 1.1 2003/03/14 20:03:29 tong Exp $
unalias *

#set nonomatch

if ($#argv != 2) then
        echo 'u64txt [RGBA, YUV, CI, IA, I, A] [4, 8, 16, 32]'
else
        set names = `ls *.rgba *.rgb *.inta *.ia *.i`
        foreach name ($names)
                rgb2c -F -f $argv[1] -s $argv[2] "$name" > $name:r.c
                chg static '\/\/' $name:r.c
                chg gsSP '\/\/' $name:r.c
                chg texture $name:r_txt $name:r.c
                chg '\.' _ $name:r.c
        end
        u64cc
endif
