/*
 * Do not edit this file.  It was automatically generated
 * by "rgb2c" from the file "/home/tong/mario/z_ocarina2/i10n/assets/zh/TEXTURE/DMA_MAKE/ICON_ITEM/gameover/.inta.inta".
 *
 *   ERROR: Texture file "/home/tong/mario/z_ocarina2/i10n/assets/zh/TEXTURE/DMA_MAKE/ICON_ITEM/gameover/.inta.inta" not found.
 */

