#!/usr/local/bin/bash
#set -x
#
# $Id: obj_make,v 1.1 2003/03/10 22:59:36 tong Exp $
#
# $Log: obj_make,v $
# Revision 1.1  2003/03/10 22:59:36  tong
# Initial revision
#
# Revision 2.7  2002/05/30  04:13:59  zelda
# *** empty log message ***
#
# Revision 2.6  2002-05-29 12:54:24+09  zelda
# *** empty log message ***
#
# Revision 2.5  1998-10-28 18:33:51+09  komatu
# du_PAL.oの追加
#
# Revision 2.4  1998-10-28 13:30:23+09  okajima
# *** empty log message ***
#
# Revision 2.3  1998/10/28 03:46:57  komatu
# PAL用シェイプデータXc_pal.oの追加の間違いを修正
#
# Revision 2.2  1998-10-27 14:20:50+09  komatu
# PAL用シェイプデータXc_pal.oの追加
#
# Revision 2.1  1998-10-22 21:42:44+09  hayakawa
# ＲＯＭ出しバージョン(NTSC)
#
# Revision 1.319  1998-10-14 14:20:07+09  matutani
# Skelton.o削除
#
# Revision 1.318  1998-10-09 16:51:50+09  komatu
# gjyo_objects.o を Gjyo_objects.oに
# 改名した。
#
# Revision 1.317  1998-09-23 00:47:28+09  sumiyosi
# *** empty log message ***
#
# Revision 1.316  1998-09-18 21:44:26+09  sakakibara
# 時の歌ブロック
#
# Revision 1.315  1998-09-15 17:08:10+09  nisiwaki
# *** empty log message ***
#
# Revision 1.314  1998-09-14 15:13:35+09  takahata
# *** empty log message ***
#
# Revision 1.313  1998-09-07 11:30:40+09  sumiyosi
# *** empty log message ***
#
# Revision 1.312  1998-09-05 14:34:00+09  nisiwaki
# *** empty log message ***
#
# Revision 1.311  1998-09-03 20:16:29+09  umemiya
# 怪鳥グエー追加
#
# Revision 1.310  1998-09-02 21:47:45+09  tarukado
# *** empty log message ***
#
# Revision 1.309  1998-09-02 12:00:13+09  umemiya
# *** empty log message ***
#
# Revision 1.308  1998-09-01 17:58:15+09  takahata
# *** empty log message ***
#
# Revision 1.307  1998-09-01 09:48:11+09  yoshida
# ゴシップストーン追加
#
# Revision 1.306  1998-08-26 21:42:33+09  umemiya
# 墓下ダンジョンドア追加
#
# Revision 1.305  1998-08-26 11:15:38+09  komatu
# *** empty log message ***
#
# Revision 1.304  1998-08-26 11:05:25+09  komatu
# *** empty log message ***
#
# Revision 1.303  1998-08-26 00:34:00+09  sumiyosi
# 敵(群れ、カップル、ベビースタル、ワーウルフ)追加。
#
# Revision 1.302  1998-08-24 16:58:20+09  umemiya
# 作曲家ポウ追加
#
# Revision 1.301  1998-08-22 17:30:07+09  yoshida
# *** empty log message ***
#
# Revision 1.300  1998-08-22 17:04:24+09  okajima
# *** empty log message ***
#
# Revision 1.299  1998-08-22 15:45:36+09  takahata
# *** empty log message ***
#
# Revision 1.298  1998-08-21 21:51:07+09  komatu
# *** empty log message ***
#
# Revision 1.297  1998-08-21 15:28:02+09  takahata
# *** empty log message ***
#
# Revision 1.296  1998-08-21 14:34:59+09  okajima
# *** empty log message ***
#
# Revision 1.295  1998-08-20 15:44:28+09  nisiwaki
# Efc_Doughnut.o 追加
#
# Revision 1.294  1998-08-20 14:58:06+09  nisiwaki
# Demo_Kekkai.o 追加
#
# Revision 1.293  1998-08-20 13:56:54+09  umemiya
# フィールドポウ追加
#
# Revision 1.292  1998-08-20 11:41:00+09  kuzuhara
# ボムチュウ屋見えない壁
#
# Revision 1.291  1998-08-19 18:51:25+09  takahata
# *** empty log message ***
#
# Revision 1.290  1998-08-18 16:05:25+09  takahata
# *** empty log message ***
#
# Revision 1.289  1998-08-18 11:38:36+09  kuzuhara
# デグナッツのお面品評会
#
# Revision 1.288  1998-08-17 21:07:05+09  sakakibara
# ｓｐｏｔ１１ オブジェクト と据置の木箱追加
#
# Revision 1.287  1998-08-17 16:49:01+09  yoshida
# *** empty log message ***
#
# Revision 1.286  1998-08-17 16:46:53+09  yoshida
# *** empty log message ***
#
# Revision 1.285  1998-08-17 16:44:51+09  yoshida
# SPOT01オブジェクトその２追加
#
# Revision 1.284  1998-08-12 14:44:01+09  sakakibara
# 邪神像ダンジョン 鉄柱と鉄椅子 & ドア
#
# Revision 1.283  1998-08-11 12:54:11+09  kuzuhara
# 犬やら鶏小娘やら
#
# Revision 1.282  1998-08-10 13:46:26+09  tarukado
# *** empty log message ***
#
# Revision 1.281  1998-08-08 16:05:20+09  umemiya
# 売りナッツ追加
#
# Revision 1.280  1998-08-07 19:35:40+09  nisiwaki
# Gla 追加
#
# Revision 1.279  1998-08-07 14:33:12+09  umemiya
# SPOT00・こわれた橋追加
#
# Revision 1.278  1998-08-06 20:07:33+09  takahata
# *** empty log message ***
#
# Revision 1.277  1998-08-06 17:58:48+09  umemiya
# ヒントナッツ追加
#
# Revision 1.276  1998-08-06 17:27:19+09  sakakibara
# ｓｐｏｔ１２ オブジェクト & 汎用爆弾岩追加
#
# Revision 1.275  1998-08-06 11:40:47+09  umemiya
# SPOT05オブジェクト追加
#
# Revision 1.274  1998-08-05 18:14:16+09  kuzuhara
# ボムチュウアルバイトねーちゃん作成
#
# Revision 1.273  1998-08-04 13:12:26+09  umemiya
# ダイオクタ追加
#
# Revision 1.272  1998-08-03 17:54:46+09  nisiwaki
# SSH 追加
#
# Revision 1.271  1998-08-03 11:50:10+09  okajima
# *** empty log message ***
#
# Revision 1.270  1998-07-31 20:52:57+09  takahata
# *** empty log message ***
#
# Revision 1.269  1998-07-31 11:19:39+09  kuzuhara
# 魚追加
#
# Revision 1.268  1998-07-30 11:51:55+09  komatu
# Ecの追加
#
# Revision 1.267  1998-07-30 11:32:27+09  takahata
# *** empty log message ***
#
# Revision 1.266  1998-07-29 13:30:13+09  komatu
# Zgの追加
#
# Revision 1.265  1998-07-23 17:21:56+09  kuzuhara
# 宝箱屋作成
#
# Revision 1.264  1998-07-23 13:03:46+09  kuzuhara
# 案山子
#
# Revision 1.263  1998-07-21 16:14:43+09  kuzuhara
# ガノン２作成
#
# Revision 1.262  1998-07-21 11:27:25+09  takahata
# *** empty log message ***
#
# Revision 1.261  1998-07-20 15:57:05+09  takahata
# *** empty log message ***
#
# Revision 1.260  1998-07-20 15:12:33+09  okajima
# *** empty log message ***
#
# Revision 1.259  1998-07-20 15:00:12+09  komatu
# 大ゼルダのアニメバンクを別にした
#
# Revision 1.258  1998-07-18 15:32:37+09  nisiwaki
# *** empty log message ***
#
# Revision 1.257  1998-07-17 11:23:56+09  komatu
# *** empty log message ***
#
# Revision 1.256  1998-07-16 21:28:21+09  soejima
# *** empty log message ***
#
# Revision 1.255  1998-07-15 15:09:51+09  takahata
# *** empty log message ***
#
# Revision 1.254  1998-07-15 13:54:45+09  yoshida
# *** empty log message ***
#
# Revision 1.253  1998-07-14 19:58:36+09  nisiwaki
# js 追加
#
# Revision 1.252  1998-07-14 11:58:10+09  takahata
# *** empty log message ***
#
# Revision 1.251  1998-07-13 14:28:19+09  takahata
# *** empty log message ***
#
# Revision 1.250  1998-07-09 14:52:20+09  takahata
# *** empty log message ***
#
# Revision 1.249  1998-07-09 14:26:28+09  sumiyosi
# *** empty log message ***
#
# Revision 1.248  1998-07-08 17:03:08+09  yoshida
# 吸い込み渦 潮吹 追加
#
# Revision 1.247  1998-07-07 21:52:31+09  umemiya
# ガノン内部・オブジェ追加
#
# Revision 1.246  1998-07-03 17:16:38+09  takahata
# *** empty log message ***
#
# Revision 1.245  1998-07-02 15:53:39+09  takahata
# *** empty log message ***
#
# Revision 1.244  1998-07-02 15:47:51+09  nisiwaki
# Fu 風車小屋の男
#
# Revision 1.243  1998-06-30 17:56:20+09  nisiwaki
# *** empty log message ***
#
# Revision 1.242  1998-06-29 20:38:19+09  umemiya
# ガノン城・オブジェ追加
#
# Revision 1.241  1998-06-26 15:29:24+09  takahata
# *** empty log message ***
#
# Revision 1.240  1998-06-25 19:18:07+09  kuzuhara
# 爆破看板作成
#
# Revision 1.239  1998-06-24 20:32:24+09  okajima
# 地名テロップのテクスチャを変えた（日本語、英語混在）
#
# Revision 1.238  1998-06-24 11:46:07+09  takahata
# *** empty log message ***
#
# Revision 1.237  1998-06-23 21:56:45+09  sakakibara
# *** empty log message ***
#
# Revision 1.236  1998-06-22 16:25:36+09  sumiyosi
# インゴーとめ柵追加。
#
# Revision 1.235  1998-06-20 16:39:00+10  takahata
# *** empty log message ***
#
# Revision 1.234  1998-06-18 22:17:11+09  umemiya
# フォールマスターを新シェイプに変更
#
# Revision 1.233  1998-06-18 13:07:32+09  komatu
# OF1をけした
#
# Revision 1.232  1998-06-16 18:36:07+09  umemiya
# 墓下子供ダンジョンオブジェ追加
#
# Revision 1.231  1998-06-16 12:05:59+09  nisiwaki
# たくさん増やした
#
# Revision 1.230  1998-06-15 17:32:51+09  nisiwaki
# *** empty log message ***
#
# Revision 1.229  1998-06-15 13:27:03+09  takahata
# *** empty log message ***
#
# Revision 1.228  1998-06-15 11:44:43+09  sakakibara
# *** empty log message ***
#
# Revision 1.227  1998-06-11 09:50:02+09  nisiwaki
# すいません
#
# Revision 1.226  1998-06-10 16:26:10+09  nisiwaki
# *** empty log message ***
#
# Revision 1.225  1998-06-10 10:54:07+09  takahata
# *** empty log message ***
#
# Revision 1.224  1998-06-09 20:51:53+09  kuzuhara
# ヤブサメスコア登録
#
# Revision 1.223  1998-06-09 14:57:59+09  nisiwaki
# *** empty log message ***
#
# Revision 1.222  1998-06-08 10:44:23+09  sumiyosi
# *** empty log message ***
#
# Revision 1.221  1998-06-05 23:20:23+10  sumiyosi
# *** empty log message ***
#
# Revision 1.220  1998-06-04 16:17:06+10  yoshida
# *** empty log message ***
#
# Revision 1.219  1998-06-04 14:19:16+09  umemiya
# 墓下リレーオブジェ追加
#
# Revision 1.218  1998-06-04 13:54:41+09  takahata
# *** empty log message ***
#
# Revision 1.217  1998-06-03 23:08:45+09  yoshida
# *** empty log message ***
#
# Revision 1.216  1998-06-03 11:20:12+09  nisiwaki
# *** empty log message ***
#
# Revision 1.215  1998-06-02 09:12:38+09  sumiyosi
# 修正。
#
# Revision 1.214  1998-06-01 23:47:04+10  sumiyosi
# ねえちゃん、おじさん追加。
#
# Revision 1.213  1998-06-01 20:11:45+10  hayakawa
# object_hidan_objects[456]消した
#
# Revision 1.212  1998-06-01 16:41:50+09  sakakibara
# Ｓｐｏｔ０８ オブジェクト追加
#
# Revision 1.211  1998-05-29 13:55:38+09  takahata
# *** empty log message ***
#
# Revision 1.210  1998-05-28 13:53:29+09  takahata
# *** empty log message ***
#
# Revision 1.209  1998-05-16 11:22:16+09  iwawaki
# *** empty log message ***
#
# Revision 1.208  1998/05/13 10:28:32  takahata
# *** empty log message ***
#
# Revision 1.207  1998-05-13 15:38:56+09  takahata
# *** empty log message ***
#
# Revision 1.206  1998-05-13 10:23:43+09  nisiwaki
# *** empty log message ***
#
# Revision 1.205  1998/05/12 14:19:03  sumiyosi
# *** empty log message ***
#
# Revision 1.204  1998/05/12 10:01:48  komatu
# *** empty log message ***
#
# Revision 1.203  1998-05-12 15:25:20+09  komatu
# *** empty log message ***
#
# Revision 1.202  1998-05-11 22:42:10+09  sumiyosi
# *** empty log message ***
#
# Revision 1.201  1998/05/08 05:01:34  takahata
# *** empty log message ***
#
# Revision 1.200  1998-05-07 15:06:54+09  takahata
# *** empty log message ***
#
# Revision 1.199  1998-05-06 17:39:14+09  umemiya
# 馬ジャンプ柵追加
#
# Revision 1.198  1998-05-06 15:24:14+09  sumiyosi
# キングゾーラ追加
#
# Revision 1.197  1998/04/30 00:17:16  sumiyosi
# *** empty log message ***
#
# Revision 1.196  1998/04/28 02:25:38  kuzuhara
# カカリコ、ゾーラゲート作成
#
# Revision 1.195  1998-04-24 14:15:10+09  iwawaki
# *** empty log message ***
#
# Revision 1.194  1998/04/23 09:48:50  kuzuhara
# ごめん
#
# Revision 1.193  1998-04-23 18:47:10+09  kuzuhara
# すみません
#
# Revision 1.192  1998-04-23 18:46:04+09  kuzuhara
# spot01追加
#
# Revision 1.191  1998-04-22 18:37:33+09  takahata
# *** empty log message ***
#
# Revision 1.190  1998-04-21 11:57:03+09  takahata
# *** empty log message ***
#
# Revision 1.189  1998-04-20 16:56:18+09  takahata
# *** empty log message ***
#
# Revision 1.188  1998-04-17 19:12:50+09  sakakibara
# *** empty log message ***
#
# Revision 1.187  1998/04/17 08:04:17  takahata
# *** empty log message ***
#
# Revision 1.186  1998-04-17 11:28:10+09  takahata
# *** empty log message ***
#
# Revision 1.185  1998-04-17 10:54:19+09  nisiwaki
# Demo_6K, object_demo_6k 追加
#
# Revision 1.184  1998/04/15 09:54:05  okajima
# *** empty log message ***
#
# Revision 1.183  1998/04/15 09:00:53  sumiyosi
# *** empty log message ***
#
# Revision 1.182  1998/04/15 03:07:41  nisiwaki
# 魔法関係 削除
#
# Revision 1.181  1998/04/14 09:22:47  takahata
# *** empty log message ***
#
# Revision 1.180  1998/04/14 08:48:15  okajima
# *** empty log message ***
#
# Revision 1.179  1998/04/14 08:29:44  okajima
# *** empty log message ***
#
# Revision 1.178  1998/04/13 02:33:15  takahata
# *** empty log message ***
#
# Revision 1.177  1998/04/10 05:21:18  nisiwaki
# たくさん 追加
#
# Revision 1.176  1998/04/10  02:01:50  yoshida
# マロン子供時代追加
#
# Revision 1.175  1998/04/09  03:05:41  takahata
# *** empty log message ***
#
# Revision 1.174  1998/04/08  06:14:51  takahata
# *** empty log message ***
#
# Revision 1.173  1998/04/08  02:34:48  nisiwaki
# リンクのCI化
#
# Revision 1.172  1998/04/07  09:22:54  takahata
# *** empty log message ***
#
# Revision 1.171  1998/04/07  02:20:53  kuzuhara
# アヌビス作成
#
# Revision 1.170  1998/04/06  11:43:31  tarukado
# *** empty log message ***
#
# Revision 1.169  1998/04/06  09:35:20  kuzuhara
# 削除俺様大妖精
#
# Revision 1.168  1998/04/06  07:03:40  sumiyosi
# ライクライク＆妖精の像を追加。
#
# Revision 1.167  1998/04/06  03:16:03  morita
# tw.o
#
# Revision 1.166  1998/04/06  01:37:13  kuzuhara
# 大妖精追加
#
# Revision 1.165  1998/04/04  10:58:09  matutani
# レース馬
#
# Revision 1.164  1998/04/03  02:38:04  takahata
# *** empty log message ***
#
# Revision 1.163  1998/04/01  00:50:54  yoshida
# *** empty log message ***
#
# Revision 1.162  1998/03/27  04:25:47  takahata
# *** empty log message ***
#
# Revision 1.161  1998/03/27  04:20:40  sumiyosi
# シェアード版ゴロン追加。
#
# Revision 1.160  1998/03/26  05:50:12  takahata
# *** empty log message ***
#
# Revision 1.159  1998/03/26  01:58:44  umemiya
# *** empty log message ***
#
# Revision 1.158  1998/03/25  14:00:03  umemiya
# 氷の洞窟、SPOT06オブジェクトなど追加
#
# Revision 1.157  1998/03/25  11:45:51  sumiyosi
# デクの樹Ｊｒ．追加。
#
# Revision 1.156  1998/03/25  09:53:46  takahata
# *** empty log message ***
#
# Revision 1.155  1998/03/25  03:00:43  komatu
# *** empty log message ***
#
# Revision 1.154  1998/03/24  04:06:57  komatu
# *** empty log message ***
#
# Revision 1.153  1998/03/23  09:33:41  takahata
# *** empty log message ***
#
# Revision 1.152  1998/03/23  09:29:04  sakakibara
# *** empty log message ***
#
# Revision 1.151  1998/03/23  06:04:29  takahata
# *** empty log message ***
#
# Revision 1.150  1998/03/21  06:43:33  sumiyosi
# 村人シェアード実験追加。
#
# Revision 1.149  1998/03/19  06:39:39  sakakibara
# Spot16 obj 追加
#
# Revision 1.148  1998/03/19  03:07:55  nisiwaki
# Tr.o を 追加
#
# Revision 1.147  1998/03/18  13:46:47  yoshida
# インゴー追加
#
# Revision 1.146  1998/03/17  10:40:59  takahata
# *** empty log message ***
#
# Revision 1.145  1998/03/16  05:25:59  takahata
# *** empty log message ***
#
# Revision 1.144  1998/03/16  04:58:24  komatu
# *** empty log message ***
#
# Revision 1.143  1998/03/13  10:56:27  takahata
# *** empty log message ***
#
# Revision 1.142  1998/03/13  06:32:29  takahata
# *** empty log message ***
#
# Revision 1.141  1998/03/12  12:29:10  takahata
# *** empty log message ***
#
# Revision 1.140  1998/03/11  10:04:31  takahata
# *** empty log message ***
#
# Revision 1.139  1998/03/10  12:54:28  morita
# mo
#
# Revision 1.138  1998/03/10  04:30:54  komatu
# *** empty log message ***
#
# Revision 1.137  1998/03/09  06:17:11  sakakibara
# *** empty log message ***
#
# Revision 1.136  1998/03/09  04:51:54  takahata
# *** empty log message ***
#
# Revision 1.135  1998/03/06  04:34:17  tarukado
# *** empty log message ***
#
# Revision 1.134  1998/03/04  14:00:32  yoshida
# *** empty log message ***
#
# Revision 1.133  1998/03/04  09:55:07  okajima
# *** empty log message ***
#
# Revision 1.132  1998/03/04  09:34:58  sakakibara
# *** empty log message ***
#
# Revision 1.131  1998/03/04  08:12:12  takahata
# *** empty log message ***
#
# Revision 1.130  1998/03/04  08:11:45  takahata
# *** empty log message ***
#
# Revision 1.129  1998/03/04  06:36:47  nisiwaki
# *** empty log message ***
#
# Revision 1.128  1998/03/03  14:07:27  yoshida
# *** empty log message ***
#
# Revision 1.127  1998/03/03  13:40:37  umemiya
# ブロッブ追加
#
# Revision 1.126  1998/03/03  12:45:20  umemiya
# Warningのため名前変更
#
# Revision 1.125  1998/03/03  08:38:32  nisiwaki
# *** empty log message ***
#
# Revision 1.124  1998/03/03  07:34:53  tarukado
# *** empty log message ***
#
# Revision 1.123  1998/03/02  02:09:01  umemiya
# 墓下ダンジョン・オブジェ追加
#
# Revision 1.122  1998/02/25  13:38:29  matutani
# *** empty log message ***
#
# Revision 1.121  1998/02/24  04:23:45  nisiwaki
# *** empty log message ***
#
# Revision 1.120  1998/02/21  10:41:37  tarukado
# *** empty log message ***
#
# Revision 1.119  1998/02/21  09:21:29  morita
# *** empty log message ***
#
# Revision 1.118  1998/02/20  12:40:12  umemiya
# 燭台をバンクに設定
#
# Revision 1.117  1998/02/20  07:50:43  matutani
# 魔法（炎、風、氷）
#
# Revision 1.116  1998/02/20  02:17:44  umemiya
# スポット０２オブジェクト、墓追加
#
# Revision 1.115  1998/02/19  07:32:25  nisiwaki
# ru1 を 追加
#
# Revision 1.114  1998/02/18  02:43:56  matutani
# 子馬追加
#
# Revision 1.113  1998/02/17  02:26:46  nisiwaki
# *** empty log message ***
#
# Revision 1.112  1998/02/16  09:05:52  sumiyosi
# フレイムダンサーを追加。
#
# Revision 1.111  1998/02/14  13:43:35  iwawaki
# *** empty log message ***
#
# Revision 1.110  1998/02/12  07:04:06  nisiwaki
# *** empty log message ***
#
# Revision 1.109  1998/02/12  02:43:54  morita
# fd追加
#
# Revision 1.108  1998/02/03  07:06:47  tarukado
# ガノン と ファントムガノンを分たっス！！
#
# Revision 1.107  1998/01/31  12:12:20  iwawaki
# *** empty log message ***
#
# Revision 1.106  1998/01/30  02:59:57  umemiya
# ポウ四姉妹追加
#
# Revision 1.105  1998/01/29  09:53:05  tarukado
# *** empty log message ***
#
# Revision 1.104  1998/01/29  07:58:52  tarukado
# *** empty log message ***
#
# Revision 1.103  1998/01/28  04:30:33  tarukado
# *** empty log message ***
#
# Revision 1.102  1998/01/27  07:00:42  umemiya
# 巨大魚ダンジョン・オブジェ追加
#
# Revision 1.101  1998/01/26  10:26:26  iwawaki
# 今寺町です
#
# Revision 1.100  1998/01/26  09:36:53  nisiwaki
# デモ用データ追加
#
# Revision 1.99  1998/01/22  12:02:35  umemiya
# 炎の輪追加
#
# Revision 1.98  1998/01/22  07:30:16  iwawaki
# *** empty log message ***
#
# Revision 1.97  1998/01/20  11:30:31  tarukado
# *** empty log message ***
#
# Revision 1.96  1998/01/20  10:34:14  tarukado
# *** empty log message ***
#
# Revision 1.95  1998/01/20  08:02:15  sumiyosi
# *** empty log message ***
#
# Revision 1.94  1998/01/19  12:34:08  umemiya
# オクタロックのデータを新規に変更
#
# Revision 1.93  1998/01/19  06:39:13  tarukado
# *** empty log message ***
#
# Revision 1.92  1998/01/14  05:51:46  tarukado
# *** empty log message ***
#
# Revision 1.91  1998/01/14  02:37:00  tarukado
# *** empty log message ***
#
# Revision 1.90  1998/01/13  14:11:20  iwawaki
# *** empty log message ***
#
# Revision 1.89  1998/01/12  14:08:35  iwawaki
# *** empty log message ***
#
# Revision 1.88  1998/01/08  10:46:44  umemiya
# 森の神殿、炎の神殿テクスチャ追加
#
# Revision 1.87  1998/01/07  06:09:59  sakakibara
# *** empty log message ***
#
# Revision 1.86  1998/01/05  05:09:33  iwawaki
# *** empty log message ***
#
# Revision 1.85  1997/12/24  06:34:10  sumiyosi
# 大ゼルダ追加
#
# Revision 1.84  1997/12/24  05:06:09  umemiya
# トラップ床ビュン追加
#
# Revision 1.83  1997/12/18  07:54:39  umemiya
# 時の間・オブジェ追加
#
# Revision 1.82  1997/12/18  06:07:05  umemiya
# *** empty log message ***
#
# Revision 1.81  1997/12/18  04:10:51  umemiya
# *** empty log message ***
#
# Revision 1.80  1997/12/17  07:03:14  tarukado
# *** empty log message ***
#
# Revision 1.79  1997/12/17  04:57:10  umemiya
# 森の神殿・ひねり回廊部屋追加
#
# Revision 1.78  1997/12/16  05:59:21  sumiyosi
# *** empty log message ***
#
# Revision 1.77  1997/12/16  00:54:29  matutani
# ファントムガノン馬
#
# Revision 1.76  1997/12/12  02:10:36  tarukado
# *** empty log message ***
#
# Revision 1.75  1997/12/12  01:52:00  tarukado
# *** empty log message ***
#
# Revision 1.74  1997/12/11  06:57:27  tarukado
# *** empty log message ***
#
# Revision 1.73  1997/12/04  09:42:29  umemiya
# 水の神殿・MOVEBGオブジェ追加
#
# Revision 1.72  1997/11/28  00:46:28  sumiyosi
# *** empty log message ***
#
# Revision 1.71  1997/11/26  07:33:26  umemiya
# バリ追加
#
# Revision 1.70  1997/11/18  04:46:20  sumiyosi
# *** empty log message ***
#
# Revision 1.69  1997/11/14  07:32:49  sumiyosi
# コキリ族軍団追加
#
# Revision 1.68  1997/11/12  08:21:34  umemiya
# 面クリダンジョンオブジェクト追加
#
# Revision 1.67  1997/11/12  07:03:41  sumiyosi
# *** empty log message ***
#
# Revision 1.66  1997/11/08  08:37:53  umemiya
# デクナッツ追加
#
# Revision 1.65  1997/11/07  04:05:52  iwawaki
# *** empty log message ***
#
# Revision 1.64  1997/10/25  05:44:13  iwawaki
# *** empty log message ***
#
# Revision 1.63  1997/10/21  09:14:32  matutani
# ゼルダ馬
#
# Revision 1.62  1997/10/20  10:45:48  sumiyosi
# ハイリア住民さらに追加。
#
# Revision 1.61  1997/10/19  09:03:22  iwawaki
# *** empty log message ***
#
# Revision 1.60  1997/10/17  08:26:27  sumiyosi
# ハイリアの住民追加。
#
# Revision 1.59  1997/10/16  08:44:16  sumiyosi
# En_GirlB→子ゼルダに変更。
#
# Revision 1.58  1997/10/08  14:18:04  sumiyosi
# インパ（マスク付）追加
#
# Revision 1.57  1997/10/08  02:28:05  sumiyosi
# ゴロン族追加
#
# Revision 1.56  1997/10/02  13:44:58  umemiya
# *** empty log message ***
#
# Revision 1.55  1997/10/02  12:40:30  umemiya
# デクババ追加
#
# Revision 1.54  1997/10/01  04:31:43  tarukado
# がノンドロフ ＆ アモス 追加
#
# Revision 1.53  1997/10/01  02:37:59  umemiya
# *** empty log message ***
#
# Revision 1.52  1997/10/01  02:26:14  hayakawa
# 日付比較コピー
#
# Revision 1.51  1997/09/29  11:50:51  umemiya
# 妖精ダンジョンオブジェ追加
#
# Revision 1.50  1997/09/29  10:54:54  sumiyosi
# コキリ族の女の子追加
#
# Revision 1.49  1997/09/27  02:05:28  hayakawa
# set -xをコメントアウトした
#
# Revision 1.48  1997/09/26  06:32:40  sumiyosi
# *** empty log message ***
#
# Revision 1.47  1997/09/24  07:30:46  tarukado
# *** empty log message ***
#
# Revision 1.46  1997/09/20  04:16:41  tarukado
# *** empty log message ***
#
# Revision 1.45  1997/09/19  08:57:12  tarukado
# *** empty log message ***
#
# Revision 1.44  1997/09/19  05:29:29  tarukado
# モリブリン追加
#
# Revision 1.43  1997/09/17  13:51:39  umemiya
# spot00オブジェ追加
#
# Revision 1.42  1997/09/17  07:24:54  sumiyosi
# *** empty log message ***
#
# Revision 1.41  1997/09/16  08:47:02  sumiyosi
# *** empty log message ***
#
# Revision 1.40  1997/09/12  12:29:05  matutani
# ガノン馬追加
#
# Revision 1.39  1997/09/11  06:45:09  umemiya
# 火の神殿オブジェ追加
#
# Revision 1.38  1997/09/09  11:54:28  iwawaki
# *** empty log message ***
#
# Revision 1.37  1997/09/05  06:37:10  sumiyosi
# *** empty log message ***
#
# Revision 1.36  1997/09/05  06:35:29  matutani
# *** empty log message ***
#
# Revision 1.35  1997/09/01  02:13:16  tarukado
# *** empty log message ***
#
# Revision 1.34  1997/09/01  01:03:48  tarukado
# *** empty log message ***
#
# Revision 1.33  1997/08/27  11:30:37  sumiyosi
# *** empty log message ***
#
# Revision 1.32  1997/08/27  06:05:06  sumiyosi
# *** empty log message ***
#
# Revision 1.31  1997/08/25  13:37:44  sumiyosi
# スタルチュラ追加。
#
# Revision 1.30  1997/08/25  01:51:32  sumiyosi
# *** empty log message ***
#
# Revision 1.29  1997/08/25  01:49:30  sumiyosi
# *** empty log message ***
#
# Revision 1.28  1997/08/25  01:48:38  hayakawa
# *** empty log message ***
#
# Revision 1.27  1997/08/19  09:46:25  tarukado
# *** empty log message ***
#
# Revision 1.26  1997/08/12  11:11:00  iwawaki
# *** empty log message ***
#
# Revision 1.25  1997/08/05  09:29:58  tarukado
# *** empty log message ***
#
# Revision 1.24  1997/08/04  02:38:22  iwawaki
# *** empty log message ***
#
# Revision 1.23  1997/07/30  01:25:20  tarukado
# *** empty log message ***
#
# Revision 1.22  1997/07/18  11:24:31  tarukado
# *** empty log message ***
#
# Revision 1.21  1997/07/18  01:16:01  tarukado
# *** empty log message ***
#
# Revision 1.20  1997/07/17  09:49:45  iwawaki
# *** empty log message ***
#
# Revision 1.19  1997/07/17  08:39:26  tarukado
# *** empty log message ***
#
# Revision 1.18  1997/07/17  06:25:26  tarukado
# *** empty log message ***
#
# Revision 1.17  1997/07/17  06:08:48  tarukado
# *** empty log message ***
#
# Revision 1.16  1997/07/17  02:50:13  tarukado
# *** empty log message ***
#
# Revision 1.15  1997/07/17  02:49:41  tarukado
# *** empty log message ***
#
# Revision 1.14  1997/07/17  02:35:34  tarukado
# *** empty log message ***
#
# Revision 1.13  1997/07/17  01:46:25  tarukado
# *** empty log message ***
#
# Revision 1.12  1997/07/09  08:37:57  sumiyosi
# *** empty log message ***
#
# Revision 1.11  1997/07/09  07:22:03  iwawaki
# *** empty log message ***
#
# Revision 1.10  1997/07/02  09:03:44  tarukado
# *** empty log message ***
#
# Revision 1.9  1997/07/02  08:04:50  tarukado
# *** empty log message ***
#
# Revision 1.8  1997/06/26  12:33:43  iwawaki
# *** empty log message ***
#
# Revision 1.7  1997/06/19  00:42:49  iwawaki
# *** empty log message ***
#
# Revision 1.6  1997/06/06  06:57:42  iwawaki
# *** empty log message ***
#
# Revision 1.5  1997/06/06  05:48:25  iwawaki
# *** empty log message ***
#
# Revision 1.4  1997/06/05  07:49:04  iwawaki
# *** empty log message ***
#
# Revision 1.3  1997/06/05  07:18:12  iwawaki
# *** empty log message ***
#
# Revision 1.2  1997/05/26  10:26:49  iwawaki
# *** empty log message ***
#
# Revision 1.1  1997/05/26  06:37:52  iwawaki
# Initial revision
#

cp2() {
  if [ ! -e $2 -o $1 -nt $2 ]; then
    echo    cp $1 $2
    command cp $1 $2
  fi
}
cp() {
  SRC=$1
  DEST=$2
  SRCBASE=`basename $SRC`
  if [ -d $DEST ]; then
    cp2 $SRC $DEST/$SRCBASE
  else
    cp2 $SRC $DEST
  fi
}

     cp shape/zelda_field_keep/zelda_field_keep.o Field_keep.o
     cp shape/zelda_dangeon_keep/zelda_dangeon_keep.o Dangeon_keep.o
     cp shape/zelda_link_new/Anime_Data/Anime_Data.o Link_anime_data.o

#     cp shape/zelda_link_ci/Boy/Boy.o Link_boy.o
#     cp shape/zelda_link_ci/Child/Child.o Link_child.o

     cp shape/zelda_link_new/Skeleton/Boy/Boy.o Link_boy.o
     cp shape/zelda_link_new/Skeleton/Child/Child.o Link_child.o
#     cp /home/nisiwaki/ZELDA/LINK/Boy/Boy.o Link_boy.o
#     cp /home/nisiwaki/ZELDA/LINK/Child/Child.o Link_child.o

#     cp /home/yoshida/gamegen/cnv/LINK/main/Boy/Boy.o Link_boy.o
#     cp /home/yoshida/gamegen/cnv/LINK/main/Child/Child.o Link_child.o

     cp shape/zelda_baby_skel/zelda_baby_skel.o Baby_skel.o 
     cp shape/zelda_box/zelda_box.o Box.o
     cp shape/zelda_dodongo/zelda_dodongo.o Dodongo.o
     cp shape/zelda_fire/zelda_fire.o Fire.o
     cp shape/zelda_human/zelda_human.o Human.o
     cp shape/zelda_ironknack/zelda_ironknack.o Ironknack.o
     cp shape/zelda_nw/zelda_nw.o Niw.o
#     cp shape/zelda_rock/zelda_rock.o Rock.o
#     cp shape/zelda_skelton/zelda_skelton.o Skelton.o
     cp shape/zelda_slime/zelda_slime.o Slime.o
     cp shape/zelda_soldier/zelda_soldier.o Soldier.o
     cp shape/zelda_st/zelda_st.o St.o
     cp shape/zelda_tt/zelda_tt.o Tite.o
     cp shape/zelda_rb/zelda_rb.o Reeba.o
     cp shape/zelda_ph/zelda_ph.o Peehat.o
     cp shape/zelda_horse/zelda_horse.o Horse.o
     cp shape/zelda_zf/zelda_zf.o Zf.o
     cp shape/zelda_goma/zelda_goma.o Go.o
     cp shape/zelda_goma_PAL/zelda_goma_PAL.o Go_PAL.o
     cp shape/zelda_kdodongo/zelda_kdodongo.o Kdodongo.o
     cp shape/zelda_kdodongo_PAL/zelda_kdodongo_PAL.o Kdodongo_PAL.o
     cp shape/zelda_zl1/zelda_zl1.o Zl1.o
     cp shape/zelda_ff/zelda_ff.o Ff.o
     cp shape/zelda_wm2/zelda_wm2.o Wm.o
     cp shape/zelda_po/zelda_po.o Po.o
     cp shape/zelda_oAx/zelda_oAx.o OAX.o
     cp shape/zelda_oc2/zelda_oc2.o Oc.o
     cp shape/zelda_tg2/zelda_tg2.o Tg2.o
     cp shape/zelda_kogoma/zelda_kogoma.o Gol.o
     cp shape/zelda_bubble/zelda_bubble.o Bubble.o
     cp shape/zelda_dodojr/zelda_dodojr.o Dodojr.o
#     cp shape/zelda_torch2/zelda_torch2.o Torch2.o
     cp shape/zelda_black_link/zelda_black_link.o Torch2.o
     cp shape/zelda_bl/zelda_bl.o Bl.o
     cp shape/zelda_tp/zelda_tp.o Tp.o
     cp shape/zelda_bw/zelda_bw.o Bw.o
     cp shape/zelda_ei/zelda_ei.o Ei.o
     cp shape/zelda_horse_normal/zelda_horse_normal.o Horse_Normal.o
     cp shape/zelda_oBx/zelda_oBx.o OBX.o
     cp shape/zelda_o_anime/zelda_o_anime.o O_anime.o
     cp shape/zelda_spo04_objects/zelda_spo04_objects.o spot04_objects.o
     cp shape/zelda_ddan_objects/zelda_ddan_objects.o ddan_objects.o
     cp shape/zelda_hidan_objects/zelda_hidan_objects.o hidan_objects.o
     cp shape/zelda_horse_ganon/zelda_horse_ganon.o Horse_Ganon.o
#     cp shape/zelda_oF1/zelda_oF1.o OF1.o
     cp shape/zelda_oA2/zelda_oA2.o OA2.o
     cp shape/zelda_spot00_objects/zelda_spot00_objects.o spot00_objects.o
     cp shape/zelda_mb/zelda_mb.o Mb.o
     cp shape/zelda_bombf/zelda_bombf.o Bombf.o
     cp shape/zelda_sk2/zelda_sk2.o Sk2.o
     cp shape/zelda_oE1/zelda_oE1.o OE1.o
     cp shape/zelda_oE_anime/zelda_oE_anime.o OE_anime.o
     cp shape/zelda_oE2/zelda_oE2.o OE2.o
     cp shape/zelda_ydan_objects/zelda_ydan_objects.o ydan_objects.o
     cp shape/zelda_gnd/zelda_gnd.o Gnd.o
     cp shape/zelda_am/zelda_am.o Am.o
     cp shape/zelda_dekubaba/zelda_dekubaba.o Dekubaba.o
     cp shape/zelda_oA3/zelda_oA3.o OA3.o
     cp shape/zelda_oA4/zelda_oA4.o OA4.o
     cp shape/zelda_oA5/zelda_oA5.o OA5.o
     cp shape/zelda_oA6/zelda_oA6.o OA6.o
     cp shape/zelda_oA7/zelda_oA7.o OA7.o
     cp shape/zelda_jj/zelda_jj.o Jj.o
     cp shape/zelda_oA8/zelda_oA8.o OA8.o
     cp shape/zelda_oA9/zelda_oA9.o OA9.o
     cp shape/zelda_oB2/zelda_oB2.o OB2.o
     cp shape/zelda_oB3/zelda_oB3.o OB3.o
     cp shape/zelda_oB4/zelda_oB4.o OB4.o
     cp shape/zelda_horse_zelda/zelda_horse_zelda.o Horse_Zelda.o
     cp shape/zelda_opdemo1/zelda_opdemo1.o Opening_Demo1.o
     cp shape/zelda_warp1/zelda_warp1.o Warp1.o
     cp shape/zelda_b_heart/zelda_b_heart.o B_heart.o
     cp shape/zelda_dekunuts/zelda_dekunuts.o Dekunuts.o
     cp shape/zelda_oE3/zelda_oE3.o OE3.o
     cp shape/zelda_oE4/zelda_oE4.o OE4.o
     cp shape/zelda_menkuri_objects/zelda_menkuri_objects.o menkuri_objects.o
     cp shape/zelda_oE5/zelda_oE5.o OE5.o
     cp shape/zelda_oE6/zelda_oE6.o OE6.o
     cp shape/zelda_oE7/zelda_oE7.o OE7.o
     cp shape/zelda_oE8/zelda_oE8.o OE8.o
     cp shape/zelda_oE9/zelda_oE9.o OE9.o
     cp shape/zelda_oE10/zelda_oE10.o OE10.o
     cp shape/zelda_oE11/zelda_oE11.o OE11.o
     cp shape/zelda_oE12/zelda_oE12.o OE12.o
     cp shape/zelda_vali/zelda_vali.o Vali.o
     cp shape/zelda_oA10/zelda_oA10.o OA10.o
     cp shape/zelda_oA11/zelda_oA11.o OA11.o
     cp shape/zelda_mizu_objects/zelda_mizu_objects.o mizu_objects.o
     cp shape/zelda_fantomHG/zelda_fantomHG.o FantomHG.o
     cp shape/zelda_fantomHG_PAL/zelda_fantomHG_PAL.o FantomHG_PAL.o
#     cp shape/zelda_oB1/zelda_oB1.o OB1.o
     cp shape/zelda_sh/zelda_sh.o OB1.o
     cp shape/zelda_mori_hineri1/zelda_mori_hineri1.o mori_hineri1.o
     cp shape/zelda_bb/zelda_bb.o Bb.o
     cp shape/zelda_toki_objects/zelda_toki_objects.o toki_objects.o
     cp shape/zelda_yukabyun/zelda_yukabyun.o Yukabyun.o
     cp shape/zelda_zl2/zelda_zl2.o Zl2.o
     cp shape/zelda_mjin/zelda_mjin.o Mjin.o
     cp shape/zelda_mjin_flash/zelda_mjin_flash.o Flash_mjin.o
     cp shape/zelda_mjin_dark/zelda_mjin_dark.o Dark_mjin.o
     cp shape/zelda_mjin_flame/zelda_mjin_flame.o Flame_mjin.o
     cp shape/zelda_mjin_ice/zelda_mjin_ice.o Ice_mjin.o
     cp shape/zelda_mjin_soul/zelda_mjin_soul.o Soul_mjin.o
     cp shape/zelda_mjin_wind/zelda_mjin_wind.o Wind_mjin.o
     cp shape/zelda_mjin_oka/zelda_mjin_oka.o Oka_mjin.o
     cp shape/zelda_spot06_objects/zelda_spot06_objects.o spot06_objects.o
     cp shape/zelda_ice_objects/zelda_ice_objects.o ice_objects.o
     cp shape/zelda_mori_hineri1a/zelda_mori_hineri1a.o mori_hineri1a.o
     cp shape/zelda_mori_hineri2/zelda_mori_hineri2.o mori_hineri2.o
     cp shape/zelda_mori_hineri2a/zelda_mori_hineri2a.o mori_hineri2a.o
     cp shape/zelda_mori_objects/zelda_mori_objects.o mori_objects.o
     cp shape/zelda_mori_tex/zelda_mori_tex.o mori_tex.o
     cp shape/zelda_spot08_obj/zelda_spot08_obj.o spot08_obj.o
     cp shape/zelda_warp2/zelda_warp2.o Warp2.o
     cp shape/zelda_hata/zelda_hata.o Hata.o
     cp shape/zelda_bird/zelda_bird.o Bird.o
     cp shape/zelda_stree/zelda_stree.o Stree.o
     cp shape/zelda_kui/zelda_kui.o Kui.o
     cp shape/zelda_maruta/zelda_maruta.o Maruta.o
     cp shape/zelda_saku/zelda_saku.o Saku.o
     cp shape/zelda_wood02/zelda_wood02.o Wood02.o
     cp shape/zelda_t_wood01/zelda_t_wood01.o Twood01.o
     cp shape/zelda_kabu02/zelda_kabu02.o Kabu02.o
     cp shape/dk_board/dk_board.o Board.o
     cp shape/dk_floater/dk_floater.o Floater.o
     cp shape/dk_lightbox/dk_lightbox.o Lightbox.o
     cp shape/dk_pu_box/dk_pu_box.o Pu_box.o
     cp shape/dk_spia/dk_spia.o Spia.o
     cp shape/dk_stonebridge/dk_stonebridge.o Stonebridge.o
     cp shape/dk_trap/dk_trap.o Trap.o
     cp shape/dk_vase/dk_vase.o Vase.o
     cp shape/zelda_im/zelda_im.o Im.o
     cp shape/zelda_xc/zelda_xc.o Xc.o
     cp shape/zelda_xc_pal/zelda_xc_pal.o Xc_pal.o
     cp shape/zelda_ta/zelda_ta.o Ta.o
     cp shape/zelda_tk/zelda_tk.o Tk.o
     cp shape/zelda_vm/zelda_vm.o Vm.o
     cp shape/zelda_bv/zelda_bv.o Bv.o
     cp shape/zelda_bv_PAL/zelda_bv_PAL.o Bv_PAL.o
#     cp shape/zelda_firecircle/zelda_firecircle.o  Firecircle.o
     cp shape/zelda_efc_crystal_light/zelda_efc_crystal_light.o  efc_crystal_light.o
     cp shape/zelda_efc_fire_ball/zelda_efc_fire_ball.o  efc_fire_ball.o
     cp shape/zelda_efc_flash/zelda_efc_flash.o   efc_flash.o
     cp shape/zelda_efc_lgt_shower/zelda_efc_lgt_shower.o   efc_lgt_shower.o
     cp shape/zelda_efc_star_field/zelda_efc_star_field.o   efc_star_field.o
     cp shape/zelda_god_lgt/zelda_god_lgt.o god_lgt.o   
     cp shape/zelda_light_ring/zelda_light_ring.o light_ring.o   
     cp shape/zelda_triforce_spot/zelda_triforce_spot.o  triforce_spot.o
     cp shape/zelda_bdan_objects/zelda_bdan_objects.o bdan_objects.o
     cp shape/zelda_sd/zelda_sd.o Sd.o
     cp shape/zelda_rd/zelda_rd.o Rd.o
     cp shape/zelda_po_sisters/zelda_po_sisters.o Po_Sisters.o
     cp shape/zelda_heavy_object/zelda_heavy_object.o Heavy_object.o
     cp shape/zelda_gndd/zelda_gndd.o Gndd.o
     cp shape/zelda_fd/zelda_fd.o fd.o
     cp shape/zelda_fd_PAL/zelda_fd_PAL.o fd_PAL.o
     cp shape/zelda_du/zelda_du.o du.o
     cp shape/zelda_du_PAL/zelda_du_PAL.o du_PAL.o
     cp shape/zelda_fw/zelda_fw.o fw.o
     cp shape/zelda_medal/medal.o medal.o
     cp shape/zelda_hlc/zelda_hlc.o hlc.o
     cp shape/zelda_ru1/zelda_ru1.o ru1.o
     cp shape/zelda_spot02_objects/zelda_spot02_objects.o spot02_objects.o
     cp shape/zelda_haka/zelda_haka.o Haka.o
#     cp shape/zelda_magic_wind/zelda_magic_wind.o magic_wind.o
#     cp shape/zelda_magic_fire/zelda_magic_fire.o magic_fire.o
#     cp shape/zelda_magic_ice/zelda_magic_ice.o magic_ice.o
     cp shape/zelda_syokudai/zelda_syokudai.o syokudai.o
     cp shape/zelda_vba/zelda_vba.o fd2.o
     cp shape/zelda_dh/zelda_dh.o Dh.o
     cp shape/zelda_efc_tw/zelda_efc_tw.o efc_tw.o
     cp shape/zelda_rl/zelda_rl.o Rl.o
     cp shape/zelda_tre_lgt/zelda_tre_lgt.o demo_tre_lgt.o
     cp shape/zelda_haka_objects/zelda_haka_objects.o haka_objects.o
     cp shape/zelda_key/zelda_key.o gi_key.o
     cp shape/zelda_mir_ray/zelda_mir_ray.o mir_ray.o
     cp shape/zelda_brob/zelda_brob.o Brob.o
     cp shape/zelda_gi_jewel/zelda_gi_jewel.o gi_jewel.o
     cp shape/zelda_spot09_obj/zelda_spot09_obj.o spot09_obj.o
     cp shape/zelda_spot18_obj/zelda_spot18_obj.o spot18_obj.o
     cp shape/zelda_boss_door/zelda_boss_door.o bdoor.o
#     cp shape/zelda_va/zelda_va.o Va.o
     cp shape/zelda_shop_tana/zelda_shop_tana.o shop_dungen.o
     cp shape/zelda_spot17_obj/zelda_spot17_obj.o spot17_obj.o
     cp shape/zelda_nb/zelda_nb.o nb.o
     cp shape/zelda_mo/zelda_mo.o mo.o
     cp shape/zelda_mo_PAL/zelda_mo_PAL.o mo_PAL.o
     cp shape/zelda_sb/zelda_sb.o sb.o
     cp shape/zelda_gi_melody/zelda_gi_melody.o gi_melody.o
     cp shape/zelda_gi_heart/zelda_gi_heart.o gi_heart.o
     cp shape/zelda_gi_compass/zelda_gi_compass.o gi_compass.o
     cp shape/zelda_gi_bosskey/zelda_gi_bosskey.o gi_bosskey.o
     cp shape/zelda_gi_medal/zelda_gi_medal.o gi_medal.o
     cp shape/zelda_gi_nuts/zelda_gi_nuts.o gi_nuts.o
     cp shape/zelda_sa/zelda_sa.o sa.o
     cp shape/zelda_gi_hearts/zelda_gi_hearts.o gi_hearts.o
     cp shape/zelda_gi_arrowcase/zelda_gi_arrowcase.o gi_arrowcase.o
     cp shape/zelda_gi_bombpouch/zelda_gi_bombpouch.o gi_bombpouch.o
     cp shape/zelda_in/zelda_in.o In.o
     cp shape/zelda_tr/zelda_tr.o Tr.o
     cp shape/zelda_spot16_obj/zelda_spot16_obj.o spot16_obj.o
     cp shape/zelda_oE1s/zelda_oE1s.o oE1s.o
     cp shape/zelda_oE4s/zelda_oE4s.o oE4s.o
     cp shape/zelda_os_anime/zelda_os_anime.o os_anime.o
     cp shape/zelda_gi_bottle/zelda_gi_bottle.o gi_bottle.o
     cp shape/zelda_dy_obj/zelda_dy_obj.o dy_obj.o
     cp shape/zelda_gi_stick/zelda_gi_stick.o gi_stick.o
     cp shape/zelda_gi_map/zelda_gi_map.o gi_map.o
     cp shape/zelda_oF1d/zelda_oF1d.o oF1d_map.o
     cp shape/zelda_ru2/zelda_ru2.o ru2.o
     cp shape/zelda_gi_shield_1/zelda_gi_shield_1.o gi_shield_1.o
     cp shape/zelda_dekujr/zelda_dekujr.o dekujr.o
     cp shape/zelda_gi_magicpot/zelda_gi_magicpot.o gi_magicpot.o
     cp shape/zelda_gi_bomb_1/zelda_gi_bomb_1.o gi_bomb_1.o
     cp shape/zelda_oF1s/zelda_oF1s.o oF1s.o
     cp shape/zelda_ma2/zelda_ma2.o Ma2.o
     cp shape/zelda_gi_purse/zelda_gi_purse.o gi_purse.o
     cp shape/zelda_hni/zelda_hni.o Hni.o
     cp shape/zelda_tw/zelda_tw.o tw.o
     cp shape/zelda_tw_PAL/zelda_tw_PAL.o tw_PAL.o
     cp shape/zelda_rr/zelda_rr.o rr.o
     cp shape/zelda_bxa/zelda_bxa.o bxa.o
     cp shape/zelda_av/zelda_av.o Av.o
     cp shape/zelda_gi_gerudo/zelda_gi_gerudo.o gi_gerudo.o
     cp shape/zelda_gi_arrow/zelda_gi_arrow.o gi_arrow.o
     cp shape/zelda_gi_bomb_2/zelda_gi_bomb_2.o gi_bomb_2.o
     cp shape/zelda_gi_egg/zelda_gi_egg.o gi_egg.o
     cp shape/zelda_gi_scale/zelda_gi_scale.o gi_scale.o
     cp shape/zelda_gi_shield_2/zelda_gi_shield_2.o gi_shield_2.o
     cp shape/zelda_gi_hookshot/zelda_gi_hookshot.o gi_hookshot.o
     cp shape/zelda_gi_ocarina/zelda_gi_ocarina.o gi_ocarina.o
     cp shape/zelda_gi_milk/zelda_gi_milk.o gi_milk.o
     cp shape/zelda_ma1/zelda_ma1.o Ma1.o
     cp shape/zelda_ganon/zelda_ganon.o B_ganon.o
     cp shape/zelda_ganon_PAL/zelda_ganon_PAL.o B_ganon_PAL.o
     cp shape/zelda_ganon_anime1/zelda_ganon_anime1.o Ganon_Anime1.o
     cp shape/zelda_ganon_anime2/zelda_ganon_anime2.o Ganon_Anime2.o
     cp shape/zelda_ganon_anime3/zelda_ganon_anime3.o Ganon_Anime3.o
     cp shape/zelda_sst/zelda_sst.o Sst.o
     cp shape/zelda_sst_PAL/zelda_sst_PAL.o Sst_PAL.o
     cp shape/zelda_go2/zelda_go2.o Go2.o
     cp shape/zelda_stk/zelda_stk.o Stk.o
     cp shape/zelda_ny/zelda_ny.o Ny.o
     cp shape/zelda_fr/zelda_fr.o Fr.o
     cp shape/zelda_gi_pachinko/zelda_gi_pachinko.o gi_pachinko.o
     cp shape/zelda_gi_boomerang/zelda_gi_boomerang.o gi_boomerang.o
     cp shape/zelda_gi_bow/zelda_gi_bow.o gi_bow.o
     cp shape/zelda_gi_glasses/zelda_gi_glasses.o gi_glasses.o
     cp shape/zelda_scene_name2/G_pn_01/G_pn_01.o .
     cp shape/zelda_scene_name2/G_pn_02/G_pn_02.o .
     cp shape/zelda_scene_name2/G_pn_03/G_pn_03.o .
     cp shape/zelda_scene_name2/G_pn_04/G_pn_04.o .
     cp shape/zelda_scene_name2/G_pn_05/G_pn_05.o .
     cp shape/zelda_scene_name2/G_pn_06/G_pn_06.o .
     cp shape/zelda_scene_name2/G_pn_07/G_pn_07.o .
     cp shape/zelda_scene_name2/G_pn_08/G_pn_08.o .
     cp shape/zelda_scene_name2/G_pn_09/G_pn_09.o .
     cp shape/zelda_scene_name2/G_pn_10/G_pn_10.o .
     cp shape/zelda_scene_name2/G_pn_11/G_pn_11.o .
     cp shape/zelda_scene_name2/G_pn_12/G_pn_12.o .
     cp shape/zelda_scene_name2/G_pn_13/G_pn_13.o .
     cp shape/zelda_scene_name2/G_pn_14/G_pn_14.o .
     cp shape/zelda_scene_name2/G_pn_15/G_pn_15.o .
     cp shape/zelda_scene_name2/G_pn_16/G_pn_16.o .
     cp shape/zelda_scene_name2/G_pn_17/G_pn_17.o .
     cp shape/zelda_scene_name2/G_pn_18/G_pn_18.o .
     cp shape/zelda_scene_name2/G_pn_19/G_pn_19.o .
     cp shape/zelda_scene_name2/G_pn_20/G_pn_20.o .
     cp shape/zelda_scene_name2/G_pn_21/G_pn_21.o .
     cp shape/zelda_scene_name2/G_pn_22/G_pn_22.o .
     cp shape/zelda_scene_name2/G_pn_23/G_pn_23.o .
     cp shape/zelda_scene_name2/G_pn_24/G_pn_24.o .
     cp shape/zelda_scene_name2/G_pn_25/G_pn_25.o .
     cp shape/zelda_scene_name2/G_pn_26/G_pn_26.o .
     cp shape/zelda_scene_name2/G_pn_27/G_pn_27.o .
     cp shape/zelda_scene_name2/G_pn_28/G_pn_28.o .
     cp shape/zelda_scene_name2/G_pn_29/G_pn_29.o .
     cp shape/zelda_scene_name2/G_pn_30/G_pn_30.o .
     cp shape/zelda_scene_name2/G_pn_31/G_pn_31.o .
     cp shape/zelda_scene_name2/G_pn_32/G_pn_32.o .
     cp shape/zelda_scene_name2/G_pn_33/G_pn_33.o .
     cp shape/zelda_scene_name2/G_pn_34/G_pn_34.o .
     cp shape/zelda_scene_name2/G_pn_35/G_pn_35.o .
     cp shape/zelda_scene_name2/G_pn_36/G_pn_36.o .
     cp shape/zelda_scene_name2/G_pn_37/G_pn_37.o .
     cp shape/zelda_scene_name2/G_pn_38/G_pn_38.o .
     cp shape/zelda_scene_name2/G_pn_39/G_pn_39.o .
     cp shape/zelda_scene_name2/G_pn_40/G_pn_40.o .
     cp shape/zelda_scene_name2/G_pn_41/G_pn_41.o .
     cp shape/zelda_scene_name2/G_pn_42/G_pn_42.o .
     cp shape/zelda_scene_name2/G_pn_43/G_pn_43.o .
     cp shape/zelda_scene_name2/G_pn_44/G_pn_44.o .
     cp shape/zelda_scene_name2/G_pn_45/G_pn_45.o .
     cp shape/zelda_scene_name2/G_pn_46/G_pn_46.o .
     cp shape/zelda_scene_name2/G_pn_47/G_pn_47.o .
     cp shape/zelda_scene_name2/G_pn_48/G_pn_48.o .
     cp shape/zelda_scene_name2/G_pn_49/G_pn_49.o .
     cp shape/zelda_scene_name2/G_pn_50/G_pn_50.o .
     cp shape/zelda_scene_name2/G_pn_51/G_pn_51.o .
     cp shape/zelda_scene_name2/G_pn_52/G_pn_52.o .
     cp shape/zelda_scene_name2/G_pn_53/G_pn_53.o .
     cp shape/zelda_scene_name2/G_pn_54/G_pn_54.o .
     cp shape/zelda_scene_name2/G_pn_55/G_pn_55.o .
     cp shape/zelda_scene_name2/G_pn_56/G_pn_56.o .
     cp shape/zelda_scene_name2/G_pn_57/G_pn_57.o .
     cp shape/zelda_scene_name_PAL/G_pn_01/G_pn_01.o G_pn_01_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_02/G_pn_02.o G_pn_02_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_03/G_pn_03.o G_pn_03_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_04/G_pn_04.o G_pn_04_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_05/G_pn_05.o G_pn_05_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_06/G_pn_06.o G_pn_06_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_07/G_pn_07.o G_pn_07_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_08/G_pn_08.o G_pn_08_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_09/G_pn_09.o G_pn_09_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_10/G_pn_10.o G_pn_10_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_11/G_pn_11.o G_pn_11_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_12/G_pn_12.o G_pn_12_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_13/G_pn_13.o G_pn_13_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_14/G_pn_14.o G_pn_14_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_15/G_pn_15.o G_pn_15_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_16/G_pn_16.o G_pn_16_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_17/G_pn_17.o G_pn_17_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_18/G_pn_18.o G_pn_18_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_19/G_pn_19.o G_pn_19_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_20/G_pn_20.o G_pn_20_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_21/G_pn_21.o G_pn_21_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_22/G_pn_22.o G_pn_22_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_23/G_pn_23.o G_pn_23_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_24/G_pn_24.o G_pn_24_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_25/G_pn_25.o G_pn_25_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_26/G_pn_26.o G_pn_26_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_27/G_pn_27.o G_pn_27_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_28/G_pn_28.o G_pn_28_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_29/G_pn_29.o G_pn_29_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_30/G_pn_30.o G_pn_30_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_31/G_pn_31.o G_pn_31_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_32/G_pn_32.o G_pn_32_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_33/G_pn_33.o G_pn_33_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_34/G_pn_34.o G_pn_34_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_35/G_pn_35.o G_pn_35_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_36/G_pn_36.o G_pn_36_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_37/G_pn_37.o G_pn_37_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_38/G_pn_38.o G_pn_38_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_39/G_pn_39.o G_pn_39_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_40/G_pn_40.o G_pn_40_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_41/G_pn_41.o G_pn_41_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_42/G_pn_42.o G_pn_42_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_43/G_pn_43.o G_pn_43_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_44/G_pn_44.o G_pn_44_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_45/G_pn_45.o G_pn_45_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_46/G_pn_46.o G_pn_46_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_47/G_pn_47.o G_pn_47_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_48/G_pn_48.o G_pn_48_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_49/G_pn_49.o G_pn_49_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_50/G_pn_50.o G_pn_50_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_51/G_pn_51.o G_pn_51_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_52/G_pn_52.o G_pn_52_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_53/G_pn_53.o G_pn_53_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_54/G_pn_54.o G_pn_54_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_55/G_pn_55.o G_pn_55_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_56/G_pn_56.o G_pn_56_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_57/G_pn_57.o G_pn_57_PAL.o
     cp shape/zelda_gi_liquid/zelda_gi_liquid.o gi_liquid.o
     cp shape/zelda_ani/zelda_ani.o ani.o
     cp shape/zelda_demo_6k/zelda_demo_6k.o D6k.o
     cp shape/zelda_gi_shield_3/zelda_gi_shield_3.o gi_shield_3.o
     cp shape/zelda_gi_letter/zelda_gi_letter.o gi_letter.o
     cp shape/zelda_spot15_obj/zelda_spot15_obj.o spot15_obj.o
     cp shape/zelda_jya_obj/zelda_jya_obj.o jya_obj.o
     cp shape/zelda_gi_clothes/zelda_gi_clothes.o gi_clothes.o
     cp shape/zelda_gi_bean/zelda_gi_bean.o gi_bean.o
     cp shape/zelda_gi_fish/zelda_gi_fish.o gi_fish.o
     cp shape/zelda_gi_saw/zelda_gi_saw.o gi_saw.o
     cp shape/zelda_gi_hammer/zelda_gi_hammer.o gi_hammer.o
     cp shape/zelda_gi_grass/zelda_gi_grass.o gi_grass.o
     cp shape/zelda_gi_longsword/zelda_gi_longsword.o gi_longsword.o
     cp shape/zelda_spot01_objects/zelda_spot01_objects.o spot01_objects.o
     cp shape/zelda_gate/zelda_gate.o Gate.o
     cp shape/zelda_md/zelda_md.o Md.o
     cp shape/zelda_km1/zelda_km1.o Km1.o
     cp shape/zelda_kw1/zelda_kw1.o Kw1.o
     cp shape/zelda_zo/zelda_zo.o Zo.o
     cp shape/zelda_kz/zelda_kz.o Kz.o
     cp shape/zelda_umajump/zelda_umajump.o Umajump.o
     cp shape/zelda_masterkokiri/zelda_masterkokiri.o masterkokiri.o
     cp shape/zelda_masterkokirihead/zelda_masterkokirihead.o masterkokirihead.o
     cp shape/zelda_mastergolon/zelda_mastergolon.o mastergolon.o
     cp shape/zelda_masterzoora/zelda_masterzoora.o masterzoora.o
     cp shape/zelda_aob/zelda_aob.o Aob.o
     cp shape/zelda_ik/zelda_ik.o Ik.o
     cp shape/zelda_ahg/zelda_ahg.o Ahg.o
     cp shape/zelda_cne/zelda_cne.o Cne.o
#     cp shape/zelda_gi_niwatori/zelda_gi_niwatori.o gi_niwatori.o
     cp shape/zelda_gi_chicken/zelda_gi_chicken.o gi_niwatori.o
     cp shape/zelda_skj/zelda_skj.o Skj.o
     cp shape/zelda_gi_bottle_letter/zelda_gi_bottle_letter.o gi_bottle_letter.o
     cp shape/zelda_bji/zelda_bji.o Bji.o
     cp shape/zelda_bba/zelda_bba.o Bba.o
     cp shape/zelda_gi_ocarina_0/zelda_gi_ocarina_0.o gi_ocarina_0.o
     cp shape/zelda_ds/zelda_ds.o Ds.o
     cp shape/zelda_ane/zelda_ane.o Ane.o
     cp shape/zelda_boj/zelda_boj.o Boj.o
     cp shape/zelda_elf_message/field/field.o EM_field.o
     cp shape/zelda_elf_message/ydan/ydan.o EM_ydan.o
     cp shape/zelda_spot03_object/zelda_spot03_object.o spot03_object.o
     cp shape/zelda_spot07_object/zelda_spot07_object.o spot07_object.o
     cp shape/zelda_fz/zelda_fz.o Fz.o
     cp shape/zelda_relay_objects/zelda_relay_objects.o relay_objects.o
     cp shape/zelda_bob/zelda_bob.o Bob.o
     cp shape/zelda_ge1/zelda_ge1.o Ge1.o
     cp shape/zelda_yabusame_point/zelda_yabusame_point.o yabusame_point.o
     cp shape/zelda_gi_boots_2/zelda_gi_boots_2.o gi_boots_2.o
     cp shape/zelda_gi_seed/zelda_gi_seed.o gi_seed.o
     cp shape/zelda_gnd_magic/zelda_gnd_magic.o gnd_magic.o
     cp shape/zelda_d_elevator/zelda_d_elevator.o d_elevator.o
     cp shape/zelda_d_hsblock/zelda_d_hsblock.o d_hsblock.o
     cp shape/zelda_d_lift/zelda_d_lift.o d_lift.o
     cp shape/zelda_mamenoki/zelda_mamenoki.o mamenoki.o
     cp shape/zelda_goroiwa/zelda_goroiwa.o goroiwa.o
#     cp shape/zelda_gi_milk_2/zelda_gi_milk_2.o gi_milk_2.o
     cp shape/zelda_toryo/zelda_toryo.o toryo.o
     cp shape/zelda_daiku/zelda_daiku.o daiku.o
     cp shape/zelda_stopge/zelda_stopge.o stopge.o
     cp shape/zelda_nwc/zelda_nwc.o nwc.o
     cp shape/zelda_blkobj/zelda_blkobj.o blkobj.o
     cp shape/zelda_hakach_objects/zelda_hakach_objects.o hakach_objects.o
     cp shape/zelda_gm/zelda_gm.o gm.o
     cp shape/zelda_ms/zelda_ms.o ms.o
     cp shape/zelda_hs/zelda_hs.o hs.o
     cp shape/zelda_ingate/zelda_ingate.o Ingate.o
     cp shape/zelda_lightswitch/zelda_lightswitch.o lightswitch.o
     cp shape/zelda_kusa/zelda_kusa.o kusa.o
     cp shape/zelda_tsubo/zelda_tsubo.o tsubo.o
     cp shape/zelda_gi_gloves/zelda_gi_gloves.o gi_gloves.o
     cp shape/zelda_gi_coin/zelda_gi_coin.o gi_coin.o
     cp shape/zelda_kanban/zelda_kanban.o kanban.o
     cp shape/zelda_gjyo_objects/zelda_gjyo_objects.o Gjyo_objects.o
     cp shape/zelda_owl/zelda_owl.o Owl.o
     cp shape/zelda_mk/zelda_mk.o Mk.o
     cp shape/zelda_fu/zelda_fu.o Fu.o
     cp shape/zelda_gi_ki_tan_mask/zelda_gi_ki_tan_mask.o gi_ki_tan_mask.o 
     cp shape/zelda_gi_redead_mask/zelda_gi_redead_mask.o gi_redead_mask.o
     cp shape/zelda_gi_skj_mask/zelda_gi_skj_mask.o gi_skj_mask.o
     cp shape/zelda_gi_rabit_mask/zelda_gi_rabit_mask.o gi_rabit_mask.o
     cp shape/zelda_gi_truth_mask/zelda_gi_truth_mask.o gi_truth_mask.o
     cp shape/zelda_ganon_objects/zelda_ganon_objects.o ganon_objects.o
     cp shape/zelda_siofuki/zelda_siofuki.o siofuki.o
     cp shape/zelda_stream/zelda_stream.o stream.o
     cp shape/zelda_mm/zelda_mm.o mm.o
     cp shape/zelda_fa/zelda_fa.o fa.o
     cp shape/zelda_os/zelda_os.o os.o
     cp shape/zelda_gi_eye_lotion/zelda_gi_eye_lotion.o gi_eye_lotion.o
     cp shape/zelda_gi_powder/zelda_gi_powder.o gi_powder.o
     cp shape/zelda_gi_mushroom/zelda_gi_mushroom.o gi_mushroom.o
     cp shape/zelda_gi_ticketstone/zelda_gi_ticketstone.o gi_ticketstone.o
     cp shape/zelda_gi_brokensword/zelda_gi_brokensword.o gi_brokensword.o
     cp shape/zelda_js/zelda_js.o Js.o
     cp shape/zelda_cs/zelda_cs.o cs.o
     cp shape/zelda_gi_prescription/zelda_gi_prescription.o gi_prescription.o
     cp shape/zelda_gi_bracelet/zelda_gi_bracelet.o gi_bracelet.o
     cp shape/zelda_gi_soldout/zelda_gi_soldout.o gi_soldout.o
     cp shape/zelda_gi_frog/zelda_gi_frog.o gi_frog.o
     cp shape/zelda_mag/zelda_mag.o mag.o
     cp shape/zelda_door_gerudo/zelda_door_gerudo.o door_gerudo.o
     cp shape/zelda_gt/zelda_gt.o gt.o
     cp shape/zelda_efc_erupc/zelda_efc_erupc.o efc_erupc.o
     cp shape/zelda_zl2_anime1/zelda_zl2_anime1.o Zl2_Anime1.o
     cp shape/zelda_zl2_anime2/zelda_zl2_anime2.o Zl2_Anime2.o
     cp shape/zelda_gi_golonmask/zelda_gi_golonmask.o gi_golonmask.o
     cp shape/zelda_gi_zoramask/zelda_gi_zoramask.o gi_zoramask.o
     cp shape/zelda_gi_gerudomask/zelda_gi_gerudomask.o gi_gerudomask.o
     cp shape/zelda_ganon2/zelda_ganon2.o B_ganon2.o
     cp shape/zelda_ganon2_PAL/zelda_ganon2_PAL.o B_ganon2_PAL.o
     cp shape/zelda_ka/zelda_ka.o Ka.o
     cp shape/zelda_ts/zelda_ts.o Ts.o
     cp shape/zelda_zg/zelda_zg.o Zg.o
     cp shape/zelda_gi_hoverboots/zelda_gi_hoverboots.o gi_hoverboots.o
     cp shape/zelda_gi_m_arrow/zelda_gi_m_arrow.o gi_m_arrow.o
     cp shape/zelda_ds2/zelda_ds2.o Ds2.o
     cp shape/zelda_ec/zelda_ec.o Ec.o
     cp shape/zelda_fishing/zelda_fishing.o Fish.o
     cp shape/zelda_gi_sutaru/zelda_gi_sutaru.o gi_sutaru.o
     cp shape/zelda_gi_goddess/zelda_gi_goddess.o gi_goddess.o
     cp shape/zelda_ssh/zelda_ssh.o ssh.o
     cp shape/zelda_ocd/zelda_ocd.o Ocd.o
     cp shape/zelda_bg/zelda_bg.o Bg.o
     cp shape/zelda_spot05_objects/zelda_spot05_objects.o spot05_objects.o
     cp shape/zelda_spot12_obj/zelda_spot12_obj.o spot12_obj.o
     cp shape/zelda_bombiwa/zelda_bombiwa.o bombiwa.o
     cp shape/zelda_hintnuts/zelda_hintnuts.o Hintnuts.o
     cp shape/zelda_rs/zelda_rs.o Rs.o
     cp shape/zelda_spot00_break/zelda_spot00_break.o spot00_break.o
     cp shape/zelda_gla/zelda_gla.o Gla.o
     cp shape/zelda_shopnuts/zelda_shopnuts.o Shopnuts.o
     cp shape/zelda_gelb/zelda_gelb.o Gelb.o
     cp shape/zelda_gr/zelda_gr.o Gr.o
     cp shape/zelda_dog/zelda_dog.o Dog.o
     cp shape/zelda_jya_iron/zelda_jya_iron.o jya_iron.o
     cp shape/zelda_jya_door/zelda_jya_door.o jya_door.o
     cp shape/zelda_spot01_objects2/zelda_spot01_objects2.o spot01_objects2.o
     cp shape/zelda_spot11_obj/zelda_spot11_obj.o spot11_obj.o
     cp shape/zelda_kibako2/zelda_kibako2.o kibako2.o
     cp shape/zelda_dns/zelda_dns.o Dns.o
     cp shape/zelda_dnk/zelda_dnk.o Dnk.o
     cp shape/zelda_gi_fire/zelda_gi_fire.o gi_fire.o
     cp shape/zelda_gi_insect/zelda_gi_insect.o gi_insect.o
     cp shape/zelda_gi_butterfly/zelda_gi_butterfly.o gi_butterfly.o
     cp shape/zelda_gi_ghost/zelda_gi_ghost.o gi_ghost.o
     cp shape/zelda_gi_soul/zelda_gi_soul.o gi_soul.o
     cp shape/zelda_bowl/zelda_bowl.o Bowl.o
     cp shape/zelda_po_field/zelda_po_field.o Po_Field.o
     cp shape/zelda_demo_kekkai/zelda_demo_kekkai.o Demo_Kekkai.o
     cp shape/zelda_efc_doughnut/zelda_efc_doughnut.o Efc_Doughnut.o
     cp shape/zelda_gi_dekupouch/zelda_gi_dekupouch.o gi_dekupouch.o
     cp shape/zelda_gi_rupy/zelda_gi_rupy.o gi_rupy.o
     cp shape/zelda_spot01_matoya/zelda_spot01_matoya.o spot01_matoya.o
     cp shape/zelda_spot01_matoyab/zelda_spot01_matoyab.o spot01_matoyab.o
     cp shape/zelda_po_composer/zelda_po_composer.o Po_Composer.o
     cp shape/zelda_mu/zelda_mu.o Mu.o
     cp shape/zelda_wf/zelda_wf.o Wf.o
     cp shape/zelda_skb/zelda_skb.o Skb.o
     cp shape/zelda_gj/zelda_gj.o gj.o
     cp shape/zelda_geff/zelda_geff.o geff.o
     cp shape/zelda_haka_door/zelda_haka_door.o haka_door.o
     cp shape/zelda_gs/zelda_gs.o gs.o
     cp shape/zelda_ps/zelda_ps.o ps.o
     cp shape/zelda_bwall/zelda_bwall.o Bwall.o
     cp shape/zelda_crow/zelda_crow.o Crow.o
     cp shape/zelda_cow/zelda_cow.o Cow.o
     cp shape/zelda_cob/zelda_cob.o Cob.o
     cp shape/zelda_gi_sword_1/zelda_gi_sword_1.o gi_sword_1.o
     cp shape/zelda_killer_door/zelda_killer_door.o killer_door.o
     cp shape/zelda_ouke_haka/zelda_ouke_haka.o ouke_haka.o
     cp shape/zelda_timeblock/zelda_timeblock.o timeblock.o
     cp shape/zelda_zl4/zelda_zl4.o Zl4.o
