#!/bin/sh
# $Id: rmfiles,v 1.1 2003/03/10 22:42:52 tong Exp $
#
# 削除するファイルの登録
# 登録は後ろに追加するようにし、
# １ヶ月をめどに消去するつもりだったが、
# めんどくさいので、数が増えすぎるまでやりません。
#
# $Log: rmfiles,v $
# Revision 1.1  2003/03/10 22:42:52  tong
# Initial revision
#
# Revision 2.3  1998-11-12 13:51:10+09  hayakawa
# z_n64dd_sjis.c
#
# Revision 2.2  1998-10-23 18:05:01+09  hayakawa
# z_en_butterfly_shape.h
# z_en_dodongo2.h
# z_forward.c
# db_objcamchk.c
# camera.odb
#
# Revision 2.1  1998-10-22 20:41:56+09  zelda
# ＲＯＭ出しバージョン(NTSC)
#
# Revision 1.91  1998/10/15 02:41:28  hayakawa
# z_segment_decl.c追加
# 古いファイルを削除
#
# Revision 1.90  1998-10-14 14:20:29+09  matutani
# z_en_skeleton,z_en_warp_boxを消しました。
#
# Revision 1.89  1998-10-13 22:53:19+09  sumiyosi
# *** empty log message ***
#
# Revision 1.88  1998-09-30 21:28:04+09  takahata
# *** empty log message ***
#
# Revision 1.87  1998-09-19 14:49:50+09  soejima
# *** empty log message ***
#
# Revision 1.86  1998-09-03 23:12:37+09  hayakawa
# rom_f rom_s rom_x対応
#
# Revision 1.85  1998-09-03 00:17:04+09  tarukado
# *** empty log message ***
#
# Revision 1.84  1998-08-28 16:06:34+09  umemiya
# オクタ岩登録
#
# Revision 1.83  1998-08-19 21:18:05+09  kuzuhara
# デグナッツボールいらんし。
#
# Revision 1.82  1998-08-04 21:56:29+09  umemiya
# 墓下蜘蛛の登録
#
# Revision 1.81  1998-07-17 13:54:48+09  komatu
# zl22の追加
#
# Revision 1.80  1998-06-26 21:51:48+09  hayakawa
# MapCommonInfo.h
#
# Revision 1.79  1998-06-25 15:32:32+09  tarukado
# 旧 敵 追加
#
# Revision 1.78  1998-06-23 13:20:12+09  soejima
# z_message_NES.c
#
# Revision 1.77  1998-06-18 13:08:22+09  komatu
# demo_nbをけした
#
# Revision 1.76  1998-06-16 15:06:49+09  kuzuhara
# *** empty log message ***
#
# Revision 1.75  1998-05-26 20:54:18+09  hayakawa
# *** empty log message ***
#
# Revision 1.74  1998-05-21 20:41:15+09  soejima
# z_parameter_map.c
#
# Revision 1.73  1998-05-14 21:16:02+09  soejima
# z_vr_boxd.h
#
# Revision 1.72  1998-05-06 09:47:11+09  kuzuhara
# 間違えて「奥様便利ファイル」をあげてしまった
#
# Revision 1.71  1998-05-01 16:02:48+09  umemiya
# z_actor_all.h追加
#
# Revision 1.70  1998-04-17 16:36:01+09  umemiya
# z_bg_ice_trap追加
#
# Revision 1.69  1998-04-16 10:27:24+10  sumiyosi
# *** empty log message ***
#
# Revision 1.68  1998/04/15 04:33:12  sumiyosi
# *** empty log message ***
#
# Revision 1.67  1998/04/15 04:28:54  hayakawa
# 追加＆更新
#
# Revision 1.66  1998-04-10 21:17:59+09  sumiyosi
# *** empty log message ***
#
# Revision 1.65  1998/04/06  08:04:53  kuzuhara
# 大妖精俺様版クリア
# 設定して３０分の命でした。
# ディレクターきどりで、俺の仕事欄に
# バカバカはるのはいいが、
# 周囲も確認してからにしてくれ！
#
# Revision 1.64  1998/04/02  11:16:29  hayakawa
# *** empty log message ***
#
# Revision 1.63  1998/03/31  12:47:37  hayakawa
# z_en_slim登録
#
# Revision 1.62  1998/03/30  06:04:39  kuzuhara
# 間違えてチェックアウトしてしまった
#
# Revision 1.61  1998/03/23  06:24:41  sakakibara
# *** empty log message ***
#
# Revision 1.60  1998/03/21  09:12:10  sumiyosi
# いろいろといらないファイル追加しました。
#
# Revision 1.59  1998/03/19  01:29:39  sumiyosi
# いろいろといらないファイル追加しました。
#
# Revision 1.58  1998/03/17  10:24:06  iwawaki
# common_texture.hを追加
#
# Revision 1.57  1998/02/25  12:06:57  hayakawa
# *** empty log message ***
#
# Revision 1.56  1998/02/17  11:28:25  hayakawa
# *** empty log message ***
#
# Revision 1.55  1998/02/17  11:23:50  hayakawa
# *** empty log message ***
#
# Revision 1.54  1998/02/13  12:59:47  tarukado
# *** empty log message ***
#
# Revision 1.53  1998/01/13  11:54:18  soejima
# z_eeprom
#
# Revision 1.52  1998/01/13  03:11:28  hayakawa
# pad
#
# Revision 1.51  1998/01/09  09:18:57  hayakawa
# z_en_girl追加
#
# Revision 1.50  1998/01/06  10:10:25  soejima
# z_save_area.h
#
# Revision 1.49  1997/12/26  00:10:23  soejima
# z_file_choose_show.c
#
# Revision 1.48  1997/12/12  06:51:50  hayakawa
# stackcheck
#
# Revision 1.47  1997/11/20  06:49:45  hayakawa
# *** empty log message ***
#
# Revision 1.46  1997/11/16  13:40:33  hayakawa
# dmamgr
#
# Revision 1.45  1997/11/15  13:23:37  hayakawa
# game.c.~1.58~
#
# Revision 1.44  1997/11/10  06:38:34  matutani
# z_bgcheck_bsp削除
#
# Revision 1.43  1997/10/24  02:28:50  hayakawa
# zzzpl.c
#
# Revision 1.42  1997/10/13  13:11:41  soejima
# kanrom.s kanrom2.s z_message_data.c
#
# Revision 1.41  1997/10/07  01:38:55  soejima
# *** empty log message ***
#
# Revision 1.40  1997/09/16  08:42:51  sumiyosi
# *** empty log message ***
#
# Revision 1.39  1997/09/13  04:34:28  umemiya
# *** empty log message ***
#
# Revision 1.38  1997/08/21  02:58:24  hayakawa
# *** empty log message ***
#
# Revision 1.37  1997/08/21  01:03:53  hayakawa
# z_segment_decl説明
#
# Revision 1.36  1997/08/08  10:24:24  soejima
# z_vr_business
#
# Revision 1.35  1997/08/07  11:36:49  ogawa
# camera.zdb削除
#
# Revision 1.34  1997/08/07  01:56:49  soejima
# *** empty log message ***
#
# Revision 1.33  1997/08/06  08:00:45  hayakawa
# *** empty log message ***
#
# Revision 1.32  1997/08/06  07:43:51  hayakawa
# Makedependの中の削除したファイルだけを消去するようにしました。
#
# Revision 1.31  1997/08/01  05:22:17  soejima
# 必ず『rm rom_d/Makedepend』実行されるようした。
#
# Revision 1.30  1997/07/31  10:00:46  soejima
# z_nameset
# z_copy_del
#
# Revision 1.29  1997/07/24  08:05:03  hayakawa
# camera_param_data.hの削除
# メッセージ追加
#
# Revision 1.28  1997/07/16  05:41:28  hayakawa
# fatan3をfatan2に変更する警告
#
# Revision 1.27  1997/07/02  05:49:15  ogawa
# camera.zdb追加
#
# Revision 1.26  1997/07/01  05:59:19  ogawa
# camera_param_data.h追加
#
# Revision 1.25  1997/06/30  10:28:30  soejima
# *** empty log message ***
#
# Revision 1.24  1997/06/26  04:24:53  soejima
# z_kankyoXXXX.cとz_kankyo_dataXXXX.cを削除
#
# Revision 1.23  1997/06/23  00:53:26  matutani
# 馬のデータのの残りを登録（skin_horse_wait_gfx_mesh,
# skin_horse_wait_skin_mesh)
#
# Revision 1.22  1997/06/20  09:34:19  matutani
# sys_short_slist登録間違い
#
# Revision 1.21  1997/06/20  05:05:16  soejima
# z_vr_box_vtxdt.c
#
# Revision 1.20  1997/06/19  00:48:40  matutani
# 馬を消す
#
# Revision 1.19  1997/06/18  13:07:17  matutani
# sys_short_slistをbgcheckに吸収
#
# Revision 1.18  1997/06/03  07:10:51  iwawaki
# *** empty log message ***
#
# Revision 1.17  1997/05/29  08:17:10  soejima
# z_title_h.hとz_title_data.[ch]
#
# Revision 1.16  1997/05/21  01:27:14  soejima
# *** empty log message ***
#
# Revision 1.15  1997/05/15  01:55:27  soejima
# z_kaleido_scope_dl と z_kaleido_scope.c.~1.32~ 削除
#
# Revision 1.14  1997/05/14  11:15:51  soejima
# *** empty log message ***
#
# Revision 1.13  1997/05/14  02:17:20  soejima
# z_title_dl.cを削除
#
# Revision 1.12  1997/05/08  04:51:06  hayakawa
# 早川よりお知らせ を削除
#
# Revision 1.11  1997/05/06  07:52:02  iwawaki
# *** empty log message ***
#
# Revision 1.10  1997/04/24  02:03:00  matutani
# 間違ってチェックインした馬のデータを削除（エラーにはならない）
#
# Revision 1.9  1997/03/29  13:04:12  hayakawa
# 早川よりお知らせ
#
# Revision 1.8  1997/03/27  02:31:53  hayakawa
# 説明表示
#
# Revision 1.7  1997/03/27  01:45:52  hayakawa
# z_kscope.c
#
# Revision 1.6  1997/03/27  01:42:52  hayakawa
# z_kscope.c
#
# Revision 1.5  1997/03/17  00:59:10  hayakawa
# spec.foxaudioを追加
#
# Revision 1.4  1997/02/14  07:29:50  hayakawa
# 登録を簡単にした
#
# Revision 1.3  1997/01/14  00:57:50  hayakawa
# gfxprint追加
# rm に -f 追加
#
# Revision 1.2  1996/12/04  06:01:56  hayakawa
# *** empty log message ***
#
# Revision 1.1  1996/12/04  05:21:50  hayakawa
# Initial revision
#

#set -x

#
# file.c と file.h の両方を消す場合は file の部分だけをここに登録してください 
#
RMFILES_CH="
z_en_npc
z_en_npc2
z_en_npc3
z_en_oA1
z_en_skeleton
z_en_warp_box
"
#
#それ以外のファイルはここに登録
#
RMFILES="
z_n64dd_sjis.c
z_en_butterfly_shape.h
z_en_dodongo2.h
z_forward.c
db_objcamchk.c
camera.odb
z_en_npc_shape.h
z_en_npc2_shape.h
z_en_npc3_shape.h
z_en_npc_move.c
z_en_npc_data.c
z_en_npc_tool.c
z_en_oA1_shape.h
z_en_skeleton_shape.h
z_segment_decl.c
"
###include.hayakawa

echo "使用しなくなったソースを削除します…"

backup_depend() {
  if [ -f $1 ]
  then
    echo $1 を /tmp/rmfiles_$1.$$ にバックアップします
    cp $1 /tmp/rmfiles_$1.$$
  fi
}

delete_depend() {
  if [ -f $2 ]
  then
    echo "$1 を $2 から抹消します (s! $1 ! !)"
    sed -e "s! $1 ! !" $2 > /tmp/rmfiles.$$
    cp /tmp/rmfiles.$$ $2
    rm -f /tmp/rmfiles.$$
  fi
}

delete_depend2() {
  if [ -f $2 ]
  then
    echo "$1 を $2 から抹消します (s! \.\./$1 ! !)"
    sed -e "s! \.\./$1 ! !" $2 > /tmp/rmfiles.$$
    cp /tmp/rmfiles.$$ $2
    rm -f /tmp/rmfiles.$$
  fi
}

delete_source() {
  if [ -f $1 ]
  then
    delete_depend $1 Makedepend
    delete_depend2 $1 rom_d/Makedepend
    delete_depend2 $1 rom_x/Makedepend
    delete_depend2 $1 rom_f/Makedepend
    delete_depend2 $1 rom_s/Makedepend
    delete_depend2 $1 rom_c/Makedepend
    echo $1 を 削除します
    mv $1 $1.deleted
  fi
  if [ -f RCS/$1,v ]
  then
    echo RCS/$1,v を 削除します
    mv RCS/$1,v RCS/$1,v.deleted
  fi
}

for file in $RMFILES_CH
do
    delete_source $file.c
    delete_source $file.h
done

for file in $RMFILES
do
    delete_source $file
done


echo '本当に削除するには、\\rm -f *.deleted を実行してください。'
echo ""

#echo "ここで、rmfilesの説明をします"
#echo "ＲＣＳ管理していたファイルが不要になった場合"
#echo "管理ファイルだけを消しても不十分です。"
#echo "他の人がそのファイルをチェックアウトしようとして登録されてしまうのです。"
#echo "つまり、コピーされたファイルも含め、完全に消さないとだめなのです。"
#echo "で、どうするかというとrmfilesに消したいファイル名を登録して、"
#echo "rmfilesをチェックインすれば、他の人がcoallしたときに自動的に削除されます。"
#echo "わかった？（はい／うん）"

#echo ""
#echo ""
#echo ""
#echo ""
#echo ""
